import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {loginCompanion} from './companion-login.mjs';import {createCompanionControl,CompanionBusy} from './companion-control.mjs';
function fixture({early=false,success=true,url='https://auth.openai.com/codex/device',authenticated=false}={}){const server=new EventEmitter(),calls=[];server.initialize=async()=>{};server.close=()=>{server.closed=true;};server.request=async(method,args)=>{calls.push([method,args]);if(method==='config/read')return {config:{sqlite_home:'/dedicated'}};if(method==='account/read')return {account:authenticated?{type:'chatgpt'}:null};if(method==='account/login/start'){if(early){authenticated=success;server.emit('notification',{method:'account/login/completed',params:{loginId:'attempt',success}});}return {loginId:'attempt',verificationUrl:url,userCode:'TEST-1234'};}return {};};return {server,calls,finish:()=>{authenticated=success;server.emit('notification',{method:'account/login/completed',params:{loginId:'attempt',success,error:'PRIVATE ERROR'}});}};}
const config={codexHome:'/dedicated',command:'/explicit/codex',cwd:'/work'};
test('device login uses selected isolated profile and requires account confirmation',async()=>{const f=fixture(),codes=[];await loginCompanion(config,{openServer:options=>{assert.equal(options.codexHome,'/dedicated');assert.equal(options.inheritApiKey,false);return f.server;},onCode:code=>{codes.push(code);f.finish();}});assert.deepEqual(codes,[{url:'https://auth.openai.com/codex/device',code:'TEST-1234'}]);assert.equal(f.server.closed,true);assert.equal(f.calls.filter(([m])=>m==='account/read').length,2);assert.equal(f.calls.some(([m])=>m==='turn/start'),false);});
test('early completion is not lost or displayed as a pending code',async()=>{const f=fixture({early:true});await loginCompanion(config,{openServer:()=>f.server,onCode:()=>assert.fail('Already completed')});assert.equal(f.server.listenerCount('notification'),0);});
test('cancel and timeout cancel the matching attempt and close native process',async()=>{for(const mode of ['cancel','timeout']){const f=fixture(),abort=new AbortController();await assert.rejects(loginCompanion(config,{openServer:()=>f.server,signal:abort.signal,timeoutMs:10,onCode:()=>{if(mode==='cancel')abort.abort();}}),e=>e.code===(mode==='cancel'?'LOGIN_CANCELLED':'LOGIN_TIMEOUT'));assert.ok(f.calls.some(([m,a])=>m==='account/login/cancel'&&a.loginId==='attempt'));assert.equal(f.server.closed,true);}});
test('untrusted auth URL and failed login never become success',async()=>{for(const opts of [{url:'https://foreign.invalid/codex/device'},{early:true,success:false}]){const f=fixture(opts);await assert.rejects(loginCompanion(config,{openServer:()=>f.server,onCode:()=>assert.fail('No valid pending code')}));assert.equal(f.server.closed,true);}});
test('existing account is not replaced or logged out',async()=>{const f=fixture({authenticated:true});await loginCompanion(config,{openServer:()=>f.server});assert.equal(f.calls.some(([m])=>m==='account/login/start'||m==='account/logout'),false);});
test('panel login owns the controller and removes its code after completion',async()=>{let finish,ready;const displayed=new Promise(r=>ready=r),control=createCompanionControl(config,{login:async(c,{onCode})=>{onCode({url:'https://auth.openai.com/codex/device',code:'TEST-1234'});ready();await new Promise(r=>finish=r);}});control.login();await displayed;assert.equal(control.snapshot().login.code,'TEST-1234');assert.throws(()=>control.start(),CompanionBusy);finish();await control.settled();assert.equal(control.snapshot().state,'authenticated');assert.equal(control.snapshot().login,undefined);});
test('completion from another attempt cannot authenticate this login',async()=>{const f=fixture();await assert.rejects(loginCompanion(config,{openServer:()=>f.server,timeoutMs:10,onCode:()=>f.server.emit('notification',{method:'account/login/completed',params:{loginId:'another',success:true}})}),e=>e.code==='LOGIN_TIMEOUT');});
test('success notification without an authenticated account is rejected',async()=>{const f=fixture({early:true}),request=f.server.request;f.server.request=async(m,a)=>m==='account/read'?{account:null}:request(m,a);await assert.rejects(loginCompanion(config,{openServer:()=>f.server}),e=>e.code==='LOGIN_FAILED');});
