import test from 'node:test';import assert from 'node:assert/strict';import {request as httpRequest} from 'node:http';import {startCompanionPanel} from './companion-panel.mjs';import {createCompanionControl} from './companion-control.mjs';
async function fixture(t){let starts=0;const control=createCompanionControl({}, {check:async()=>{},run:async(c,{signal,onStatus})=>{starts++;onStatus({state:'connected'});await new Promise(r=>{if(signal.aborted)r();else signal.addEventListener('abort',r,{once:true});});}});const panel=await startCompanionPanel({}, {control});t.after(()=>panel.close());return {...panel,control,starts:()=>starts};}
async function login(p){const r=await fetch(p.origin+'/api/session',{method:'POST',headers:{Origin:p.origin,'Content-Type':'application/json'},body:JSON.stringify({token:p.url.split('#')[1]})});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);return r.headers.get('set-cookie').split(';')[0];}
test('panel requires a local session, exact origin and fixed host',async t=>{const p=await fixture(t);assert.equal((await fetch(p.origin+'/api/status')).status,401);assert.equal((await fetch(p.origin+'/api/start',{method:'POST',headers:{Origin:'https://foreign.invalid','Content-Type':'application/json'},body:'{}'})).status,403);const cookie=await login(p);assert.equal((await fetch(p.origin+'/api/status',{headers:{Cookie:cookie.replace(/[a-f0-9]{64}$/,'é'.repeat(64))}})).status,401);const code=await new Promise((resolve,reject)=>{const req=httpRequest(p.origin,{headers:{Host:'foreign.invalid'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});assert.equal(code,403);assert.equal(p.starts(),0);});
test('authenticated panel starts and stops only its configured runner',async t=>{const p=await fixture(t),cookie=await login(p),post=path=>fetch(p.origin+'/api/'+path,{method:'POST',headers:{Origin:p.origin,Cookie:cookie,'Content-Type':'application/json'},body:'{}'});assert.equal((await post('start')).status,202);assert.equal((await post('start')).status,409);assert.equal(p.starts(),1);assert.equal((await post('stop')).status,202);await p.control.settled();const status=await(await fetch(p.origin+'/api/status',{headers:{Cookie:cookie}})).json();assert.equal(status.state,'stopped');assert.equal(status.active,false);assert.equal((await fetch(p.origin+'/api/start',{method:'POST',headers:{Origin:p.origin,Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify({command:'/untrusted'})})).status,400);assert.equal(p.starts(),1);});
test('panel serves restrictive CSP and keeps its capability out of HTML',async t=>{const p=await fixture(t),r=await fetch(p.origin);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('referrer-policy'),'no-referrer');assert.equal((await r.text()).includes(p.url.split('#')[1]),false);});
test('a link from another conversation cannot show this panel controls',async t=>{const sessionId='selected',url='https://lanka.example/mcp/organizations/test',p=await startCompanionPanel({sessionId,url},{control:createCompanionControl({sessionId})});t.after(()=>p.close());const mismatch=await fetch(p.origin+'/?sessionId=another');assert.equal(mismatch.status,409);assert.equal((await mismatch.text()).includes('/panel.js'),false);assert.equal((await fetch(p.origin+'/?sessionId='+sessionId+'&endpoint='+encodeURIComponent(url))).status,200);});
test('matching conversation ID on a different deployment or tenant is rejected before control UI',async t=>{const sessionId='same-conversation',url='https://production.example/mcp/organizations/tenant-a',p=await startCompanionPanel({sessionId,url},{control:createCompanionControl({sessionId,url})});t.after(()=>p.close());for(const endpoint of ['',url.replace('production','staging'),url.replace('tenant-a','tenant-b')]){const r=await fetch(p.origin+'/?sessionId='+sessionId+(endpoint?'&endpoint='+encodeURIComponent(endpoint):''));assert.equal(r.status,409);assert.equal((await r.text()).includes('/panel.js'),false);}assert.equal((await fetch(p.origin)).status,200);});

test('model endpoint accepts only an explicit model override for check or start',async t=>{
 const seen=[],config={model:'saved'},control=createCompanionControl(config,{check:async c=>seen.push(c.model),listModels:async()=>[{model:'chosen',displayName:'Chosen'}]});const p=await startCompanionPanel(config,{control});t.after(()=>p.close());const cookie=await login(p);const post=(action,body)=>fetch(p.origin+'/api/'+action,{method:'POST',headers:{Origin:p.origin,Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify(body)});
 assert.equal((await post('models',{})).status,202);await control.settled();assert.equal((await post('check',{model:'chosen'})).status,202);await control.settled();assert.deepEqual(seen,['chosen']);for(const [action,body] of [['check',{model:''}],['models',{model:'chosen'}],['start',{model:'chosen',command:'/wrong'}]])assert.equal((await post(action,body)).status,400);assert.equal(config.model,'saved');
});
test('authenticated recovery endpoint uses configured state and rejects path overrides',async t=>{let calls=0;const config={stateDir:'/selected'},control=createCompanionControl(config,{recover:async c=>{assert.equal(c.stateDir,'/selected');calls++;return {state:'locks_released',modelStarted:false};}}),p=await startCompanionPanel(config,{control});t.after(()=>p.close());const cookie=await login(p),post=body=>fetch(p.origin+'/api/recover',{method:'POST',headers:{Origin:p.origin,Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal((await post({stateDir:'/other'})).status,400);assert.equal((await post({model:'other'})).status,400);assert.equal((await post({})).status,202);await control.settled();assert.equal(control.snapshot().state,'recovered');assert.equal(calls,1);});
