import test from 'node:test';import assert from 'node:assert/strict';import {requireCompanionModel,listCompanionModels} from './companion-models.mjs';import {checkCompanionAccount} from './companion-daemon.mjs';
test('explicit model can be found on a later page and hidden entries are requested',async()=>{const requests=[];const server={request:async(method,args)=>{requests.push([method,args]);return args.cursor?{data:[{id:'different-id',model:'chosen',hidden:true}],nextCursor:null}:{data:[{model:'default',isDefault:true}],nextCursor:'next'};}};assert.deepEqual(await requireCompanionModel(server,'chosen'),{model:'chosen'});assert.equal(requests.length,2);assert.equal(requests[1][1].cursor,'next');assert.ok(requests.every(([m,a])=>m==='model/list'&&a.includeHidden===true));});
test('missing exact model is rejected without falling back to default or id alias',async()=>{await assert.rejects(requireCompanionModel({request:async()=>({data:[{id:'chosen',model:'different',isDefault:true}],nextCursor:null})},'chosen'),e=>e.code==='MODEL_UNAVAILABLE');});
test('malformed or cycling catalogs are not misreported as an unavailable model',async()=>{for(const result of [{data:null},{data:[],nextCursor:'loop'},{data:[],nextCursor:7}])await assert.rejects(requireCompanionModel({request:async()=>result},'chosen'),e=>e.code==='PROTOCOL');});
test('account preflight verifies selected model after login and closes the native process on rejection',async()=>{const calls=[];let closed=false;const server={initialize:async()=>{},request:async m=>{calls.push(m);if(m==='config/read')return {config:{sqlite_home:'/dedicated'}};if(m==='account/read')return {account:{type:'chatgpt'}};if(m==='model/list')return {data:[],nextCursor:null};assert.fail('Unexpected native operation');},close:()=>closed=true};await assert.rejects(checkCompanionAccount({codexHome:'/dedicated',model:'chosen'},{openServer:()=>server}),e=>e.code==='MODEL_UNAVAILABLE');assert.deepEqual(calls,['config/read','account/read','model/list']);assert.equal(closed,true);});
test('missing login prevents model lookup',async()=>{await assert.rejects(checkCompanionAccount({codexHome:'/dedicated',model:'chosen'},{openServer:()=>({initialize:async()=>{},request:async m=>{if(m==='config/read')return {config:{sqlite_home:'/dedicated'}};assert.equal(m,'account/read');return {account:null};},close:()=>{}})}),e=>e.code==='AUTH_REQUIRED');});

test('picker reads visible catalog pages without inference and exposes only model labels',async()=>{
 let closed=false;const calls=[];const result=await listCompanionModels({codexHome:'/dedicated'},{openServer:()=>({initialize:async()=>{},close:()=>closed=true,request:async(method,args)=>{calls.push(method);if(method==='config/read')return {config:{sqlite_home:'/dedicated'}};if(method==='account/read')return {account:{}};assert.equal(method,'model/list');assert.equal(args.includeHidden,false);return args.cursor?{data:[{model:'b',displayName:'Beta',secret:'omit'},{model:'hidden',hidden:true}],nextCursor:null}:{data:[{model:'a',displayName:'Alpha'}],nextCursor:'next'};}})});
 assert.deepEqual(result,[{model:'a',displayName:'Alpha'},{model:'b',displayName:'Beta'}]);assert.equal(closed,true);assert.deepEqual(calls,['config/read','account/read','model/list','model/list']);
});
test('picker requires login and closes process after rejection',async()=>{let closed=false;await assert.rejects(listCompanionModels({codexHome:'/dedicated'},{openServer:()=>({initialize:async()=>{},close:()=>closed=true,request:async method=>{if(method==='config/read')return {config:{sqlite_home:'/dedicated'}};assert.equal(method,'account/read');return {account:null};}})}),e=>e.code==='AUTH_REQUIRED');assert.equal(closed,true);});
