import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,writeFile,readFile,stat} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {configureCompanion,companionSetupCommands} from './companion-setup.mjs';import {loadCompanionConfig} from './companion-daemon.mjs';
async function fixture(t){const root=await mkdtemp(join(tmpdir(),'lanka-setup-'));t.after(()=>rm(root,{recursive:true,force:true}));const connectionPath=join(root,'download.json'),connection={format:'lanka-companion-connection/v1',url:'https://example.invalid/mcp/organizations/'+randomUUID(),token:'a'.repeat(64),sessionId:randomUUID(),expiresAt:new Date(Date.now()+60000).toISOString()};await writeFile(connectionPath,JSON.stringify(connection),{mode:0o644});return {connection,options:{connectionPath,directory:join(root,'private'),command:'/explicit/codex',codexHome:'/explicit/profile',cwd:root,model:'explicit-model'}};}
test('wizard copies portable download to private files and produces a loadable configuration',async t=>{const {connection,options}=await fixture(t),{configPath}=await configureCompanion(options),c=await loadCompanionConfig(configPath);assert.equal(c.token,connection.token);assert.equal(c.command,options.command);assert.equal(c.model,options.model);assert.equal((await stat(configPath)).mode&0o777,0o600);assert.equal((await stat(c.connectionPath)).mode&0o777,0o600);assert.equal((await stat(options.directory)).mode&0o777,0o700);assert.equal((await stat(options.connectionPath)).mode&0o777,0o644);assert.deepEqual(Object.keys(JSON.parse(await readFile(configPath,'utf8'))).sort(),['codexHome','command','connectionPath','cwd','model','stateDir']);});
test('wizard refuses expired or executable connection data before creating a directory',async t=>{const {connection,options}=await fixture(t);for(const input of [{...connection,expiresAt:'2000-01-01'},{...connection,command:'/untrusted'}]){await writeFile(options.connectionPath,JSON.stringify(input));await assert.rejects(configureCompanion(options));await assert.rejects(stat(options.directory),{code:'ENOENT'});}});
test('wizard never overwrites an existing configuration or checkpoint',async t=>{const {options}=await fixture(t),{configPath}=await configureCompanion(options),original=await readFile(configPath,'utf8');await assert.rejects(configureCompanion({...options,model:'replacement'}),{code:'EEXIST'});assert.equal(await readFile(configPath,'utf8'),original);});
import {spawnSync} from 'node:child_process';
test('printed commands pass metacharacters literally to the CLI',async t=>{
 const {options}=await fixture(t),sentinel=join(options.cwd,'injected'),path=join(options.cwd,"quote' $(touch "+sentinel+") config.json"),commands=companionSetupCommands(path);
 const result=spawnSync('/bin/sh',['-c',commands.check],{encoding:'utf8'});
 assert.equal(result.status,1);assert.equal(JSON.parse(result.stderr).code,'CONFIGURATION');await assert.rejects(stat(sentinel),{code:'ENOENT'});
});
test('default profile and workspace are new private directories without copied credentials',async t=>{const {options}=await fixture(t);delete options.codexHome;delete options.cwd;const {configPath}=await configureCompanion(options),c=await loadCompanionConfig(configPath);for(const path of [c.codexHome,c.cwd]){assert.equal((await stat(path)).mode&0o777,0o700);assert.ok(path.startsWith(await import('node:fs/promises').then(fs=>fs.realpath(options.directory))));}await assert.rejects(stat(join(c.codexHome,'auth.json')),{code:'ENOENT'});assert.equal(c.model,options.model);});
