import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';import {openCompanionJournal} from './companion-journal.mjs';import {reconcileFinishedExecution} from './companion-recovery.mjs';
async function setup(t){const dir=await mkdtemp(join(tmpdir(),'lanka-recovery-')),journal=await openCompanionJournal(join(dir,'task.json'),{sessionId:randomUUID(),messageId:randomUUID()});t.after(async()=>{await journal.close();await rm(dir,{recursive:true,force:true});});await journal.advance('claim_pending');await journal.advance('claimed');await journal.advance('start_pending');await journal.advance('running',{nativeThreadId:'thread',nativeTurnId:'turn'});await journal.advance('answer_pending',{reply:' Saved answer \n',replyRequestId:randomUUID()});await journal.advance('unknown');const s=journal.snapshot();return {journal,s,request:{id:s.messageId,role:'user',delivery:'completed',execution:{id:s.executionId,state:'stopped',reportedBy:'external_mcp_client'}},reply:{id:s.replyRequestId,replyTo:s.messageId,role:'assistant',text:'Saved answer'}};}
const response=data=>({content:[{type:'text',text:JSON.stringify(data)}]});
test('lost reply acknowledgement reconciles exact persisted response without any write RPC',async t=>{const {journal,s,request,reply}=await setup(t),calls=[];const client={call:async(name,args)=>{calls.push(name);return response({sessionId:s.sessionId,messages:[request,reply],hasMore:false});}};await reconcileFinishedExecution(client,journal);assert.equal(journal.snapshot().phase,'terminal');assert.deepEqual(calls,['lanka_read_conversation']);});
test('unconfirmed termination, mismatched response and foreign execution stay unknown',async t=>{const {journal,s,request,reply}=await setup(t);for(const messages of [[{...request,execution:{...request.execution,state:'unknown'}},reply],[request,{...reply,text:'Other'}],[{...request,execution:{...request.execution,id:randomUUID()}},reply]]){await assert.rejects(reconcileFinishedExecution({call:async()=>response({sessionId:s.sessionId,messages,hasMore:false})},journal),/reconciliation/);assert.equal(journal.snapshot().phase,'unknown');}});
test('cancelled task requires a terminal report and needs no assistant reply',async t=>{const {journal,s,request}=await setup(t);await reconcileFinishedExecution({call:async()=>response({sessionId:s.sessionId,messages:[{...request,delivery:'cancelled'}],hasMore:false})},journal);assert.equal(journal.snapshot().phase,'terminal');});
test('recovery reads all pages and refuses incomplete or wrong conversation',async t=>{const {journal,s,request,reply}=await setup(t);await assert.rejects(reconcileFinishedExecution({call:async()=>response({sessionId:randomUUID(),messages:[],hasMore:false})},journal),/mismatch/);await assert.rejects(reconcileFinishedExecution({call:async()=>response({sessionId:s.sessionId,messages:[request],hasMore:true,nextCursor:'1'})},journal),/incomplete/);const client={call:async(name,a)=>response({sessionId:s.sessionId,messages:a.after==='0'?[request]:[reply],hasMore:a.after==='0',nextCursor:'1'})};await reconcileFinishedExecution(client,journal);assert.equal(journal.snapshot().phase,'terminal');});

test('unregistered pre-start claim recovers with the same execution ID but native startup uncertainty never does',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'lanka-unstarted-')),journal=await openCompanionJournal(join(dir,'task.json'),{sessionId:randomUUID(),messageId:randomUUID()});t.after(async()=>{await journal.close();await rm(dir,{recursive:true,force:true});});await journal.advance('claim_pending');await journal.advance('unknown');const s=journal.snapshot(),client={call:async()=>response({sessionId:s.sessionId,messages:[{id:s.messageId,role:'user',delivery:'received_by_mcp_client'}],hasMore:false})};
 assert.equal(s.unknownFrom,'claim_pending');assert.equal((await reconcileFinishedExecution(client,journal)).state,'ready_to_claim');assert.equal(journal.snapshot().executionId,s.executionId);await journal.advance('claim_pending');await journal.advance('claimed');await journal.advance('start_pending');await journal.advance('unknown');await assert.rejects(reconcileFinishedExecution(client,journal),/reconciliation/);await assert.rejects(journal.advance('received'),/cannot be retried/);
});
test('registered claim or cancelled message cannot be reset as an unregistered pre-start request',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'lanka-prestart-')),journal=await openCompanionJournal(join(dir,'task.json'),{sessionId:randomUUID(),messageId:randomUUID()});t.after(async()=>{await journal.close();await rm(dir,{recursive:true,force:true});});await journal.advance('claim_pending');await journal.advance('unknown');const s=journal.snapshot();for(const fields of [{delivery:'cancelled'},{delivery:'received_by_mcp_client',execution:{id:s.executionId,state:'claimed',reportedBy:'external_mcp_client'}}])await assert.rejects(reconcileFinishedExecution({call:async()=>response({sessionId:s.sessionId,messages:[{id:s.messageId,role:'user',...fields}],hasMore:false})},journal),/reconciliation/);assert.equal(journal.snapshot().phase,'unknown');
});
