import test from 'node:test';import assert from 'node:assert/strict';import {createCompanionControl,CompanionBusy} from './companion-control.mjs';
test('one operation owns the runtime until its promise settles, including stop',async()=>{
 let finish,start;const started=new Promise(r=>start=r),control=createCompanionControl({}, {run:async(c,{signal,onStatus})=>{onStatus({state:'working',token:'not-for-ui'});start();await new Promise(r=>finish=r);assert.equal(signal.aborted,true);},check:()=>assert.fail('No concurrent check')});
 control.start();await started;assert.equal(control.snapshot().state,'working');assert.equal(JSON.stringify(control.snapshot()).includes('not-for-ui'),false);assert.throws(()=>control.start(),CompanionBusy);assert.throws(()=>control.check(),CompanionBusy);
 control.stop();assert.equal(control.snapshot().state,'stopping');assert.equal(control.snapshot().active,true);assert.throws(()=>control.start(),CompanionBusy);finish();await control.settled();assert.equal(control.snapshot().state,'stopped');assert.equal(control.snapshot().active,false);
});
test('uncertain stop stays needs_attention and never becomes stopped',async()=>{let entered;const started=new Promise(r=>entered=r),control=createCompanionControl({}, {run:async(c,{signal})=>{entered();await new Promise(r=>signal.addEventListener('abort',r,{once:true}));throw Error('private response');}});control.start();await started;control.stop();const status=await control.settled();assert.equal(status.state,'needs_attention');assert.equal(status.code,'INTERRUPTED');assert.equal(JSON.stringify(status).includes('private response'),false);});
test('connection check does not run a model or implicitly start polling',async()=>{let checks=0;const control=createCompanionControl({}, {check:async()=>{checks++;},run:()=>assert.fail('No inference')});control.check();assert.equal(control.snapshot().state,'checking');await control.settled();assert.equal(checks,1);assert.equal(control.snapshot().state,'ready');});
test('panel context exposes only selected metadata and verified title, including missing native login',async()=>{
 const config={url:'https://lanka.example/mcp/organizations/123',sessionId:'chosen',model:'explicit-model',token:'private-token',codexHome:'/private/profile',command:'/private/command'};
 const control=createCompanionControl(config,{check:async(c,{onContext})=>{onContext({sessionId:'another',title:'Wrong conversation'});assert.equal(control.snapshot().context.title,null);onContext({sessionId:'chosen',title:'Рабочая презентация',token:'other-secret'});throw Error('Native login missing');}});
 control.check();await control.settled();const s=control.snapshot();assert.equal(s.context.server,'https://lanka.example');assert.equal(s.context.title,'Рабочая презентация');assert.equal(s.context.model,'explicit-model');assert.equal(s.state,'needs_attention');for(const secret of ['private-token','/private/profile','/private/command','other-secret'])assert.equal(JSON.stringify(s).includes(secret),false);s.context.title='Mutated';assert.equal(control.snapshot().context.title,'Рабочая презентация');
});

test('explicit picker choice is used for check and run without rewriting saved configuration',async()=>{
 const config={model:'saved'},seen=[];const control=createCompanionControl(config,{listModels:async()=>[{model:'chosen',displayName:'Chosen'}],check:async c=>seen.push(c.model),run:async c=>seen.push(c.model)});
 control.models();assert.throws(()=>control.start(),CompanionBusy);await control.settled();const snapshot=control.snapshot();snapshot.models[0].model='mutated';assert.equal(control.snapshot().models[0].model,'chosen');
 control.check({model:'chosen'});await control.settled();assert.equal(control.snapshot().context.model,'chosen');control.start({model:'chosen'});await control.settled();assert.deepEqual(seen,['chosen','chosen']);assert.equal(config.model,'saved');control.start();await control.settled();assert.equal(seen.at(-1),'saved');
});
test('late successful read after cancellation cannot show ready or a new catalog',async()=>{
 for(const operation of ['check','models']){let entered,release;const ready=new Promise(r=>entered=r);const control=createCompanionControl({},{check:async()=>{entered();await new Promise(r=>release=r);},listModels:async(c,{signal})=>{assert.equal(signal.aborted,false);entered();await new Promise(r=>release=r);return [{model:'late'}];}});control[operation]();await ready;control.stop();assert.equal(control.snapshot().state,'stopping');release();await control.settled();assert.equal(control.snapshot().state,'cancelled');assert.equal(control.snapshot().active,false);assert.equal(control.snapshot().models,null);}
});
test('recovery is serialized, confirms its result and never implicitly launches an agent',async()=>{let entered,release,runs=0;const ready=new Promise(r=>entered=r),control=createCompanionControl({sessionId:'chosen'},{run:async()=>runs++,recover:async(c,{signal})=>{assert.equal(c.sessionId,'chosen');assert.equal(signal.aborted,false);entered();await new Promise(r=>release=r);return {state:'locks_released',modelStarted:false};}});control.recover();await ready;assert.equal(control.snapshot().state,'recovering');assert.throws(()=>control.start(),CompanionBusy);assert.throws(()=>control.recover(),CompanionBusy);release();await control.settled();assert.equal(control.snapshot().state,'recovered');assert.equal(runs,0);});
test('failed recovery exposes no private diagnostic and never reports success',async()=>{const control=createCompanionControl({},{recover:async()=>{throw Error('private native response');}});control.recover();await control.settled();assert.equal(control.snapshot().code,'RECOVERY_UNCONFIRMED');assert.ok(!JSON.stringify(control.snapshot()).includes('private native response'));});
