import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';import {createCompanionCodexAdapter} from './companion-codex.mjs';
async function setup(t,{verify,turn,previous}={}){
 const dir=await mkdtemp(join(tmpdir(),'lanka-native-adapter-'));t.after(()=>rm(dir,{recursive:true,force:true}));const task={sessionId:randomUUID(),messageId:randomUUID(),executionId:randomUUID()},configPath=join(dir,'config.json'),message={id:task.messageId,text:'Explain the slide',task:{mode:'discuss'}};
 await writeFile(configPath,JSON.stringify({url:'https://example.invalid/mcp/organizations/'+randomUUID(),token:'a'.repeat(64),task,mode:'discuss',readyPath:join(dir,'ready.json')}),{mode:0o600});
 const events=[],server=new EventEmitter();server.nativeThreadConfig={test:'scope'};server.start=async(...args)=>{events.push({name:'start',args});return {thread:{id:'thread'}};};server.request=async()=>({thread:{id:'thread',turns:previous??[{id:'previous-turn',status:'completed'}]}});server.resume=async(...args)=>{events.push({name:'resume',args});return {thread:{id:'thread'}};};server.close=()=>events.push({name:'close'});server.turn=async(id,prompt,o)=>{events.push({name:'turn',prompt});if(turn)return turn(server,o);await o.onStarted('turn');o.onTerminal({threadId:id,turnId:'turn',status:'completed'});return 'Done';};
 const adapter=createCompanionCodexAdapter({command:'/trusted/codex',codexHome:dir,cwd:dir,configPath,model:'explicit-test-model',...(previous?{nativeThreadId:'thread',nativeTurnId:'previous-turn'}:{})},{createClient:()=>({initialize:async()=>{},tools:async()=>[{name:'lanka_get_workspace_context',description:'Read',inputSchema:{type:'object',properties:{}}}]}),openServer:async opts=>{events.push({name:'open',opts});return server;},verifyTools:async(...args)=>{events.push({name:'verify'});await verify?.(...args);}});return {adapter,task,message,events};
}
test('adapter uses explicit isolated profile and verifies tools before inference without leaking token',async t=>{const {adapter,task,message,events}=await setup(t),native=await adapter.prepare({task,message});assert.equal(events.some(e=>e.name==='turn'),false);assert.equal(events.find(e=>e.name==='open').opts.isolatedState,true);const observed=[];assert.equal(await native.turn({onStarted:async id=>observed.push(id),onTerminal:e=>observed.push(e.status)}),'Done');assert.deepEqual(observed,['turn','completed']);assert.equal(events.find(e=>e.name==='turn').prompt.includes('a'.repeat(64)),false);await assert.rejects(native.turn({}),/already/);native.close();});
test('catalog mismatch closes native process and prevents a turn',async t=>{const {adapter,task,message,events}=await setup(t,{verify:()=>{throw Error('Catalog mismatch');}});await assert.rejects(adapter.prepare({task,message}),/mismatch/);assert.equal(events.at(-1).name,'close');assert.equal(events.some(e=>e.name==='turn'),false);});
test('task override is rejected before native initialization',async t=>{const {adapter,task,message,events}=await setup(t);await assert.rejects(adapter.prepare({task:{...task,executionId:randomUUID()},message}),/match/);assert.equal(events.length,0);});
test('unexpected native tools interrupt the current run',async t=>{const {adapter,task,message}=await setup(t,{turn:(server,o)=>{server.emit('notification',{method:'item/started',params:{threadId:'thread',item:{type:'commandExecution'}}});assert.equal(o.signal.aborted,true);throw Error('Interrupted forbidden tool');}}),native=await adapter.prepare({task,message});await assert.rejects(native.turn({}),/Interrupted/);native.close();});

test('resume reuses the exact completed native context and reapplies its scoped configuration',async t=>{const {adapter,task,message,events}=await setup(t,{previous:[{id:'previous-turn',status:'completed'}]});const native=await adapter.prepare({task,message});assert.equal(events.some(e=>e.name==='start'),false);const resume=events.find(e=>e.name==='resume');assert.deepEqual(resume.args[3].config,{test:'scope'});assert.equal(events.at(-1).name,'verify');native.close();});
test('busy or unexpectedly advanced native contexts are not resumed or interrupted automatically',async t=>{for(const previous of [[{id:'previous-turn',status:'inProgress'}],[{id:'other-turn',status:'completed'}]]){const {adapter,task,message,events}=await setup(t,{previous});await assert.rejects(adapter.prepare({task,message}),/reconciliation/);assert.equal(events.some(e=>e.name==='resume'||e.name==='turn'),false);assert.equal(events.at(-1).name,'close');}});
