import {chromium} from 'playwright';
import {mkdir} from 'node:fs/promises';
import {createServer} from 'node:http';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import {readFile} from 'node:fs/promises';import {Pool} from 'pg';import {build} from 'esbuild';
await build({stdin:{contents:"export {AgentDelegations} from './lib/adapters/postgres/agent-delegations';export {createCorporateApplication,corporateNodeHandler} from './lib/server/corporate-http';export {captureRevisionDependencies} from './lib/project/revision-dependencies';export {demoDoc,initialState} from './lib/domain/model';export {canonicalJson} from './lib/domain/canonical-json';export {OrganizationColleagueReviews} from './lib/adapters/postgres/colleague-reviews';export {PostgresResourceAccess} from './lib/adapters/postgres/resource-access';export {PostgresOrganizationAccess} from './lib/adapters/postgres/organization-access';export {PostgresBrowserIdentityStore} from './lib/adapters/postgres/browser-identity';export {writeColleagueReviewIn} from './lib/adapters/postgres/colleague-review-storage';export {applySelfHostedMigrations,assertSelfHostedSchema} from './lib/adapters/postgres/schema';",resolveDir:process.cwd()},outfile:'.project-runtime/colleague-review-storage-test.mjs',bundle:true,platform:'node',format:'esm',packages:'external',define:{__LANKA_EXPORT_BUILD__:JSON.stringify({buildHash:'0'.repeat(64),packageVersion:'test'})}});
const {AgentDelegations,createCorporateApplication,corporateNodeHandler,captureRevisionDependencies,demoDoc,initialState,canonicalJson,OrganizationColleagueReviews,PostgresResourceAccess,PostgresOrganizationAccess,PostgresBrowserIdentityStore,writeColleagueReviewIn,applySelfHostedMigrations,assertSelfHostedSchema}=await import('../../.project-runtime/colleague-review-storage-test.mjs');
test('isolated PostgreSQL: pinned FK, repeat receipts, concurrency and atomic rollback',async()=>{
 const base=JSON.parse(await readFile('work/agent-chat/config.json','utf8')),name='lanka_review_'+randomUUID().replaceAll('-',''),admin=new Pool(base.connection);let db,server,browser,created=false;
 try{
  await admin.query(`CREATE DATABASE "${name}"`);created=true;db=new Pool({...base.connection,database:name});await applySelfHostedMigrations(db);assert.equal((await assertSelfHostedSchema(db)).latest,'0036_revision_design_packages');
  const tenant=randomUUID(),documentId=randomUUID(),sender=randomUUID(),recipient=randomUUID(),outsider=randomUUID();
  const doc=demoDoc();doc.design='focus-v3';doc.id=documentId;doc.slides=doc.slides.slice(0,1);Object.assign(doc.slides[0],{sourceIds:[],metrics:[],chart:[],notes:'PRIVATE-NOTES',canvas:[{id:'title',kind:'text',text:'На проверку',x:100,y:100,w:1200,h:100,size:40,color:'#111111',font:'sans',bold:true,lineHeight:1.2}]});delete doc.slides[0].table;delete doc.slides[0].comparison;delete doc.slides[0].assetId;
  const imageBytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5WQAAAAASUVORK5CYII=','base64'),imageHash=createHash('sha256').update(imageBytes).digest('hex');
  doc.slides[0].canvas.push({id:'photo',kind:'image',x:100,y:250,w:400,h:300,assetId:'PRIVATE-IMAGE'});
  const state=initialState(doc);state.sources=[{id:'PRIVATE-IMAGE',name:'PRIVATE-FILE',kind:'image',sha256:imageHash,createdAt:'2026-09-10T00:00:00.000Z',contentType:'image/png',excerpt:'PRIVATE-EXCERPT'}];state.revision=1;const project={format:'lanka-project/v1',title:doc.title,state,receipts:[]},hash=createHash('sha256').update(canonicalJson(doc)).digest('hex');
  const identities=new PostgresBrowserIdentityStore(db),deployment=randomUUID(),users={},tokens={};
  for(const person of [sender,recipient,outsider]){const token=randomUUID();tokens[person]=token;await identities.establish(deployment,{issuer:'https://review.test',subject:person,name:'Test'},token,null,new Date(Date.now()+3600000));users[person]=await identities.authenticate(deployment,token);}
  await db.query("INSERT INTO lanka.tenants(id,slug,name,created_by,provision_hash) VALUES($1,$3,'Test',$2,'test')",[tenant,users[sender].userId,tenant]);
  for(const person of [sender,recipient,outsider]){
   await db.query("INSERT INTO lanka.principals(tenant_id,id,kind,user_id) VALUES($1,$2,'human',$3)",[tenant,person,users[person].userId]);
   await db.query("INSERT INTO lanka.organization_memberships(tenant_id,principal_id,role,status) VALUES($1,$2,$3,'active')",[tenant,person,person===sender?'owner':'member']);
  }
  await db.query('INSERT INTO lanka.materials(tenant_id,id,owner_id,project) VALUES($1,$2,$3,$4)',[tenant,documentId,sender,JSON.stringify(project)]);
  await db.query("INSERT INTO lanka.material_revisions(tenant_id,material_id,revision,hash,doc,action) VALUES($1,$2,1,$3,$4,'test')",[tenant,documentId,hash,JSON.stringify(doc)]);
  const captured=await captureRevisionDependencies(project,async()=>imageBytes);
  await db.query('INSERT INTO lanka.revision_dependency_snapshots(tenant_id,material_id,revision,document_hash,payload,bytes,hash) VALUES($1,$2,1,$3,$4,$5,$6)',[tenant,documentId,hash,JSON.stringify(captured.snapshot),captured.bytes,captured.hash]);
  for(const blob of captured.blobs)await db.query('INSERT INTO lanka.revision_dependency_blobs(tenant_id,material_id,hash,bytes) VALUES($1,$2,$3,$4)',[tenant,documentId,blob.hash,blob.bytes]);
  const context={tenantId:tenant,documentId,actorId:sender},command={action:'create',requestId:randomUUID(),recipientId:recipient,target:{revision:1,documentHash:hash},note:'Проверить'};
  const tx=async(ctx,cmd,abort=false)=>{const c=await db.connect();try{await c.query('BEGIN');const v=await writeColleagueReviewIn(c,ctx,cmd);if(abort)throw Error('abort test');await c.query('COMMIT');return v;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}};
  const [first,repeated]=await Promise.all([tx(context,command),tx(context,command)]);assert.deepEqual(first,repeated);
  await assert.rejects(()=>tx(context,{...command,note:'Изменённый повтор'}),/другие данные/);
  await assert.rejects(()=>tx(context,{...command,requestId:randomUUID(),target:{revision:2,documentHash:hash}}),e=>e.code==='23503');
  await assert.rejects(()=>tx(context,{...command,requestId:randomUUID()},true),/abort test/);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM lanka.colleague_reviews')).rows[0].n,1);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM lanka.colleague_review_receipts')).rows[0].n,1);
  const reply={action:'respond',requestId:randomUUID(),id:first.id,expectedStatusVersion:1,target:first.target,outcome:'reviewed',note:'Проверено'},recipientContext={...context,actorId:recipient};
  const outcomes=await Promise.allSettled([tx(recipientContext,reply),tx(context,{action:'cancel',requestId:randomUUID(),id:first.id,expectedStatusVersion:1})]);
  assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);assert.equal(outcomes.filter(r=>r.status==='rejected').length,1);
  const stored=(await db.query('SELECT state FROM lanka.colleague_reviews')).rows[0].state;assert.equal(stored.statusVersion,2);
  const winning=outcomes[0].status==='fulfilled'?await tx(recipientContext,reply):stored;assert.deepEqual(winning,stored);
  // The original receipt is stable even when the request later completes.
  assert.deepEqual(await tx(context,command),first);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM lanka.colleague_review_receipts')).rows[0].n,2);
  const resource=(await db.query('SELECT id FROM lanka.resource_nodes WHERE tenant_id=$1 AND material_id=$2',[tenant,documentId])).rows[0].id;
  const orgs=new PostgresOrganizationAccess(db),resources=new PostgresResourceAccess(orgs),reviews=new OrganizationColleagueReviews(resources);
  const denied=fn=>assert.rejects(async()=>await fn(),e=>[401,403,404].includes(e.status));
  const grant=async(person,role)=>resources.mutate(users[sender],tenant,{requestId:randomUUID(),command:{action:'grant',resourceId:resource,subject:{kind:'principal',id:person},role,canCopy:false}});
  const request={...command,requestId:randomUUID()};
  await denied(()=>reviews.write(users[sender],tenant,documentId,request));
  await grant(recipient,'commenter');const allowed=await reviews.write(users[sender],tenant,documentId,request);
  const view=await reviews.read(users[recipient],tenant,documentId,allowed.id);assert.equal(view.hasNewVersion,false);assert.equal(JSON.stringify(view).includes('privateMarker'),false);
  const visible=await reviews.version(users[recipient],tenant,documentId,allowed.id);assert.equal(JSON.stringify(visible.version).includes('PRIVATE-NOTES'),false);assert.equal(visible.version.document.slides[0].canvas[0].text,'На\u00a0проверку');
  await grant(outsider,'commenter');await denied(()=>reviews.read(users[outsider],tenant,documentId,allowed.id));
  await denied(()=>reviews.write({kind:'delegated',tokenHash:'a'.repeat(64)},tenant,documentId,request));
  await denied(()=>reviews.read(users[recipient],randomUUID(),documentId,allowed.id));
  await grant(recipient,null);await denied(()=>reviews.version(users[recipient],tenant,documentId,allowed.id));await denied(()=>reviews.read(users[recipient],tenant,documentId,allowed.id));await denied(()=>reviews.write(users[sender],tenant,documentId,request));
  await grant(recipient,'commenter');assert.deepEqual(await reviews.write(users[sender],tenant,documentId,request),allowed);
  await orgs.setMembership(users[sender],tenant,{requestId:randomUUID(),userId:users[recipient].userId,role:'member',status:'suspended'});
  await denied(()=>reviews.write(users[sender],tenant,documentId,request));
  await orgs.setMembership(users[sender],tenant,{requestId:randomUUID(),userId:users[recipient].userId,role:'member',status:'active'});
  const completed=await reviews.write(users[recipient],tenant,documentId,{...reply,requestId:randomUUID(),id:allowed.id});assert.equal(completed.status,'responded');
  await db.query("UPDATE lanka.materials SET project=jsonb_set(project,'{state,revision}','2') WHERE tenant_id=$1 AND id=$2",[tenant,documentId]);
  assert.equal((await reviews.read(users[recipient],tenant,documentId,allowed.id)).hasNewVersion,true);
  assert.deepEqual((await reviews.version(users[recipient],tenant,documentId,allowed.id)).version,visible.version);
  let handler;server=createServer((req,res)=>handler(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
  const auth={config:{origin},handle:async()=>null,authenticate:async req=>identities.authenticate(deployment,(req.headers.get('cookie')??'').replace(/^review-test=/,''))};
  handler=corporateNodeHandler(createCorporateApplication(auth,orgs,{runtimeRoot:'.project-runtime',assetRoot:'.project-runtime',uiRefresh:true}),origin);
  const path='/api/organizations/'+tenant+'/documents/'+documentId+'/review-requests';
  const http=(suffix='',person=sender,body,originHeader=origin)=>fetch(origin+path+suffix,{headers:{...(person?{Cookie:'review-test='+tokens[person]}:{}),Origin:originHeader,...(body?{'Content-Type':'application/json'}:{})},...(body?{method:'POST',body:JSON.stringify(body)}:{})});
  const httpCommand={...command,requestId:randomUUID()};
  assert.equal((await http('',sender,{...httpCommand,senderId:outsider})).status,400);
  assert.equal((await http('',sender,{...httpCommand,note:'x'.repeat(13000)})).status,413);
  assert.equal((await http('',null,httpCommand)).status,401);assert.equal((await http('',sender,httpCommand,'https://other.invalid')).status,403);
  const createdResponse=await http('',sender,httpCommand);assert.equal(createdResponse.status,200);const httpReview=await createdResponse.json();
  assert.deepEqual(await (await http('',sender,httpCommand)).json(),httpReview);
  const versionResponse=await http('/'+httpReview.id+'/version',recipient);assert.equal(versionResponse.status,200);assert.equal(versionResponse.headers.get('cache-control'),'no-store');
  const publicVersion=await versionResponse.json();assert.equal(JSON.stringify(publicVersion).includes('PRIVATE-'),false);assert.equal('blobs' in publicVersion,false);
  const imageId=publicVersion.version.sources.find(s=>s.kind==='image').id;
  const imageResponse=await http('/'+httpReview.id+'/assets?id='+imageId,recipient);assert.equal(imageResponse.status,200);assert.equal(imageResponse.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await imageResponse.arrayBuffer()),imageBytes);
  assert.equal((await http('/'+httpReview.id+'/assets?id=shared-slide-snapshot',recipient)).status,404);
  assert.equal((await http('/'+httpReview.id+'/version',outsider)).status,404);
  const postedAnswer=await http('',recipient,{...reply,id:httpReview.id,requestId:randomUUID()});assert.equal(postedAnswer.status,200);assert.equal((await postedAnswer.json()).status,'responded');
  const cancellable=await (await http('',sender,{...httpCommand,requestId:randomUUID()})).json();
  const cancellation=await http('',sender,{action:'cancel',requestId:randomUUID(),id:cancellable.id,expectedStatusVersion:1});assert.equal(cancellation.status,200);assert.equal((await cancellation.json()).status,'cancelled');
  const pending=[];for(let n=0;n<52;n++)pending.push(await tx(context,{...command,requestId:randomUUID()}));
  const pageOne=await (await http('',recipient)).json();assert.equal(pageOne.items.length,50);assert.ok(pageOne.nextCursor);
  const pageTwo=await (await http('?cursor='+pageOne.nextCursor+'&expectedEpoch='+pageOne.authzEpoch,recipient)).json();assert.equal(pageTwo.items.length,2);assert.equal(pageTwo.nextCursor,null);
  assert.equal(new Set([...pageOne.items,...pageTwo.items].map(r=>r.id)).size,52);
  assert.deepEqual((await (await http('',outsider)).json()).items,[]);
  assert.equal((await http('?cursor='+pageOne.nextCursor,recipient)).status,409);
  const inbox=(query='',person=recipient)=>fetch(origin+'/api/organizations/'+tenant+'/review-inbox'+query,{headers:{Cookie:'review-test='+tokens[person]}});
  const inboxResponse=await inbox();assert.equal(inboxResponse.status,200);const incoming=await inboxResponse.json();assert.equal(incoming.items.length,50);
  const incomingMore=await(await inbox('?cursor='+incoming.nextCursor+'&expectedEpoch='+incoming.authzEpoch)).json();assert.equal(incomingMore.items.length,2);assert.equal(new Set([...incoming.items,...incomingMore.items].map(r=>r.id)).size,52);
  assert.ok(incoming.items.every(r=>r.documentId===documentId));assert.equal(JSON.stringify(incoming).includes('PRIVATE-'),false);
  assert.deepEqual((await(await inbox('',outsider)).json()).items,[]);assert.deepEqual((await(await inbox('',sender)).json()).items,[]);
  assert.equal((await inbox('?cursor='+incoming.nextCursor)).status,409);
  // Inbox visibility must agree with document ACL across folder boundaries.
  await db.query("INSERT INTO lanka.workspace_catalogs(tenant_id,owner_id,origin) VALUES($1,$2,'native') ON CONFLICT DO NOTHING",[tenant,sender]);
  const reviewFolder=randomUUID();await db.query("INSERT INTO lanka.catalog_folders(tenant_id,owner_id,id,name) VALUES($1,$2,$3,'Review folder')",[tenant,sender,reviewFolder]);
  const folderResource=(await db.query('SELECT id FROM lanka.resource_nodes WHERE tenant_id=$1 AND folder_id=$2',[tenant,reviewFolder])).rows[0].id;
  const acl=command=>resources.mutate(users[sender],tenant,{requestId:randomUUID(),command});
  await acl({action:'move',resourceId:resource,parentFolderId:folderResource});
  await acl({action:'inheritance',resourceId:resource,inheritance:'inherit'});await grant(recipient,null);
  const reviewGroup=randomUUID();await acl({action:'group_set',id:reviewGroup,name:'Incoming reviewers',status:'active'});
  await acl({action:'group_member',groupId:reviewGroup,principalId:recipient,present:true});
  await acl({action:'grant',resourceId:folderResource,subject:{kind:'group',id:reviewGroup},role:'commenter',canCopy:false});
  assert.equal((await(await inbox()).json()).items.length,50);
  await acl({action:'inheritance',resourceId:resource,inheritance:'restricted'});assert.deepEqual((await(await inbox()).json()).items,[]);
  await acl({action:'inheritance',resourceId:resource,inheritance:'inherit'});
  await acl({action:'group_set',id:reviewGroup,name:'Incoming reviewers',status:'suspended'});assert.deepEqual((await(await inbox()).json()).items,[]);
  await acl({action:'group_set',id:reviewGroup,name:'Incoming reviewers',status:'active'});assert.equal((await(await inbox()).json()).items.length,50);
  await grant(recipient,'commenter');await acl({action:'inheritance',resourceId:resource,inheritance:'restricted'});
  await db.query('UPDATE lanka.resource_nodes SET deleted_at=now() WHERE tenant_id=$1 AND id=$2',[tenant,folderResource]);assert.deepEqual((await(await inbox()).json()).items,[]);
  await db.query('UPDATE lanka.resource_nodes SET deleted_at=NULL WHERE tenant_id=$1 AND id=$2',[tenant,folderResource]);assert.equal((await(await inbox()).json()).items.length,50);
  await acl({action:'move',resourceId:resource,parentFolderId:null});
  const secondDocument=randomUUID(),secondDoc={...structuredClone(doc),id:secondDocument,title:'Вторая презентация'},secondHash=createHash('sha256').update(canonicalJson(secondDoc)).digest('hex');
  const secondProject=structuredClone(project);secondProject.title=secondDoc.title;secondProject.state.doc=secondDoc;
  await db.query('INSERT INTO lanka.materials(tenant_id,id,owner_id,project) VALUES($1,$2,$3,$4)',[tenant,secondDocument,sender,JSON.stringify(secondProject)]);
  await db.query("INSERT INTO lanka.material_revisions(tenant_id,material_id,revision,hash,doc,action) VALUES($1,$2,1,$3,$4,'test')",[tenant,secondDocument,secondHash,JSON.stringify(secondDoc)]);
  const secondResource=(await db.query('SELECT id FROM lanka.resource_nodes WHERE tenant_id=$1 AND material_id=$2',[tenant,secondDocument])).rows[0].id;
  await acl({action:'grant',resourceId:secondResource,subject:{kind:'principal',id:recipient},role:'commenter',canCopy:false});
  const secondRequest=await tx({...context,documentId:secondDocument},{...command,requestId:randomUUID(),target:{revision:1,documentHash:secondHash}});
  const allIncoming=async()=>{let current=await(await inbox()).json();const items=[...current.items];while(current.nextCursor){current=await(await inbox('?cursor='+current.nextCursor+'&expectedEpoch='+current.authzEpoch)).json();items.push(...current.items);}return items;};
  assert.deepEqual(new Set((await allIncoming()).map(r=>r.documentId)),new Set([documentId,secondDocument]));
  await db.query('UPDATE lanka.materials SET trashed=true WHERE tenant_id=$1 AND id=$2',[tenant,secondDocument]);assert.equal((await allIncoming()).some(r=>r.id===secondRequest.id),false);
  await db.query('UPDATE lanka.materials SET trashed=false WHERE tenant_id=$1 AND id=$2',[tenant,secondDocument]);assert.equal((await allIncoming()).some(r=>r.id===secondRequest.id),true);
  await tx({...context,documentId:secondDocument},{action:'cancel',requestId:randomUUID(),id:secondRequest.id,expectedStatusVersion:1});assert.equal((await allIncoming()).some(r=>r.id===secondRequest.id),false);
  const keys=new AgentDelegations(resources),secret= randomUUID().replaceAll('-','')+randomUUID().replaceAll('-','');
  const issued=await keys.issue(users[sender],tenant,documentId,{requestId:randomUUID(),secret,name:'Review reader',capability:'read',minutes:30});
  const rpc=async(name,args={},token=secret,material=documentId,method='tools/call')=>{const response=await fetch(origin+'/mcp/organizations/'+tenant+(material?'/documents/'+material:''),{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-06-18'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params:method==='tools/list'?{}:{name,arguments:args}})});return {status:response.status,body:await response.json()};};
  const advertised=await rpc('',{},secret,documentId,'tools/list');assert.ok(advertised.body.result.tools.some(t=>t.name==='lanka_list_colleague_reviews'));
  const agentListing=await rpc('lanka_list_colleague_reviews',{status:'all'});assert.equal(agentListing.status,200);assert.ok(!agentListing.body.result.isError);const agentPage=JSON.parse(agentListing.body.result.content[0].text);assert.ok(agentPage.items.length);assert.equal('canRequest' in agentPage,false);
  const agentRead=await rpc('lanka_get_colleague_review',{reviewId:pending[0].id});assert.ok(!agentRead.body.result.isError);assert.equal(JSON.parse(agentRead.body.result.content[0].text).review.id,pending[0].id);assert.equal(JSON.stringify(agentRead.body).includes('PRIVATE-'),false);
  const feedback=await rpc('lanka_get_colleague_review',{reviewId:httpReview.id});const feedbackContext=JSON.parse(feedback.body.result.content[0].text);assert.equal(feedbackContext.review.status,'responded');assert.equal(feedbackContext.review.response.note,reply.note);assert.equal(feedbackContext.review.response.actorId,recipient);assert.equal(feedbackContext.review.target.documentHash,httpReview.target.documentHash);
  const wrongScope=await rpc('lanka_get_colleague_review',{reviewId:pending[0].id},secret,secondDocument);assert.ok(wrongScope.status>=400||wrongScope.body.result?.isError||wrongScope.body.error);
  const outsiderSecret=randomUUID().replaceAll('-','')+randomUUID().replaceAll('-','');await keys.issue(users[outsider],tenant,documentId,{requestId:randomUUID(),secret:outsiderSecret,name:'Other reader',capability:'read',minutes:30});
  const otherRead=await rpc('lanka_get_colleague_review',{reviewId:pending[0].id},outsiderSecret);assert.ok(otherRead.status>=400||otherRead.body.result?.isError||otherRead.body.error);
  await grant(recipient,null);const revokedParticipant=await rpc('lanka_get_colleague_review',{reviewId:pending[0].id});assert.ok(revokedParticipant.status>=400||revokedParticipant.body.result?.isError||revokedParticipant.body.error);await grant(recipient,'commenter');
  await keys.revoke(users[sender],tenant,documentId,issued.id);const revokedKey=await rpc('lanka_get_colleague_review',{reviewId:pending[0].id});assert.ok(revokedKey.status>=400||revokedKey.body.result?.isError||revokedKey.body.error);
  const workspaceSecret=randomUUID().replaceAll('-','')+randomUUID().replaceAll('-','');
  const workspaceIssued=await keys.issue(users[sender],tenant,null,{requestId:randomUUID(),secret:workspaceSecret,name:'Workspace review reader',capability:'read',minutes:30});
  const workspaceTools=await rpc('',{},workspaceSecret,null,'tools/list');assert.ok(workspaceTools.body.result.tools.find(t=>t.name==='lanka_get_colleague_review').inputSchema.required.includes('documentId'));
  const workspaceReview=await rpc('lanka_get_colleague_review',{documentId,reviewId:pending[0].id},workspaceSecret,null);assert.equal(JSON.parse(workspaceReview.body.result.content[0].text).review.id,pending[0].id);
  const missingDocument=await rpc('lanka_get_colleague_review',{reviewId:pending[0].id},workspaceSecret,null);assert.ok(missingDocument.status>=400||missingDocument.body.result?.isError||missingDocument.body.error);
  const folderSecret=randomUUID().replaceAll('-','')+randomUUID().replaceAll('-','');await keys.issue(users[sender],tenant,null,{requestId:randomUUID(),secret:folderSecret,name:'Folder review reader',capability:'read',minutes:30,folderResourceId:folderResource});
  const outOfFolder=await rpc('lanka_get_colleague_review',{documentId,reviewId:pending[0].id},folderSecret,null);assert.ok(outOfFolder.status>=400||outOfFolder.body.result?.isError||outOfFolder.body.error);
  await acl({action:'move',resourceId:resource,parentFolderId:folderResource});
  const inFolder=await rpc('lanka_get_colleague_review',{documentId,reviewId:pending[0].id},folderSecret,null);assert.equal(JSON.parse(inFolder.body.result.content[0].text).review.id,pending[0].id);
  await acl({action:'move',resourceId:resource,parentFolderId:null});const movedAway=await rpc('lanka_get_colleague_review',{documentId,reviewId:pending[0].id},folderSecret,null);assert.ok(movedAway.status>=400||movedAway.body.result?.isError||movedAway.body.error);
  await db.query("UPDATE lanka.agent_delegations SET created_at=now()-interval '1 hour',expires_at=now()-interval '1 second' WHERE tenant_id=$1 AND id=$2",[tenant,workspaceIssued.id]);
  const expired=await rpc('lanka_get_colleague_review',{documentId,reviewId:pending[0].id},workspaceSecret,null);assert.ok(expired.status>=400||expired.body.result?.isError||expired.body.error);
  const directory=async(query='')=>fetch(origin+path.replace(/review-requests$/,'review-recipients')+query,{headers:{Cookie:'review-test='+tokens[sender]}});
  const initialPeople=await (await directory()).json();assert.deepEqual(new Set(initialPeople.items.map(p=>p.id)),new Set([recipient,outsider]));
  const people=[];for(let n=0;n<52;n++){
   const person=randomUUID();people.push(person);await db.query("INSERT INTO lanka.auth_identities(id,issuer,subject,display_name) VALUES($1,'https://directory.test',$2,'Reviewer')",[person,person]);
   await db.query("INSERT INTO lanka.principals(tenant_id,id,kind,user_id) VALUES($1,$2,'human',$2)",[tenant,person]);
   await db.query("INSERT INTO lanka.organization_memberships(tenant_id,principal_id,role,status) VALUES($1,$2,'member','active')",[tenant,person]);
   if(n<51)await grant(person,'commenter');
  }
  const peopleOne=await (await directory('?search=Reviewer')).json();assert.equal(peopleOne.items.length,50);
  const peopleTwo=await (await directory('?search=Reviewer&cursor='+peopleOne.nextCursor+'&expectedEpoch='+peopleOne.authzEpoch)).json();assert.equal(peopleTwo.items.length,1);
  assert.equal(new Set([...peopleOne.items,...peopleTwo.items].map(p=>p.id)).size,51);assert.equal([...peopleOne.items,...peopleTwo.items].some(p=>p.id===people[51]),false);
  const group=randomUUID();await resources.mutate(users[sender],tenant,{requestId:randomUUID(),command:{action:'group_set',id:group,name:'Reviewers',status:'active'}});
  await resources.mutate(users[sender],tenant,{requestId:randomUUID(),command:{action:'group_member',groupId:group,principalId:people[51],present:true}});
  await resources.mutate(users[sender],tenant,{requestId:randomUUID(),command:{action:'grant',resourceId:resource,subject:{kind:'group',id:group},role:'commenter',canCopy:false}});
  const grouped=await (await directory('?search=Reviewer')).json(),groupedMore=await (await directory('?search=Reviewer&cursor='+grouped.nextCursor+'&expectedEpoch='+grouped.authzEpoch)).json();
  assert.equal([...grouped.items,...groupedMore.items].some(p=>p.id===people[51]),true);
  await resources.mutate(users[sender],tenant,{requestId:randomUUID(),command:{action:'group_set',id:group,name:'Reviewers',status:'suspended'}});
  const ungrouped=await (await directory('?search=Reviewer')).json(),ungroupedMore=await (await directory('?search=Reviewer&cursor='+ungrouped.nextCursor+'&expectedEpoch='+ungrouped.authzEpoch)).json();
  assert.equal([...ungrouped.items,...ungroupedMore.items].some(p=>p.id===people[51]),false);
  assert.equal((await http('?cursor='+pageOne.nextCursor+'&expectedEpoch='+pageOne.authzEpoch,recipient)).status,409);
  await grant(recipient,null);assert.deepEqual((await(await inbox()).json()).items,[]);assert.equal((await inbox('?cursor='+incoming.nextCursor+'&expectedEpoch='+incoming.authzEpoch)).status,409);assert.deepEqual((await (await http('',sender)).json()).items,[]);assert.ok([403,404].includes((await http('/'+httpReview.id+'/assets?id='+imageId,recipient)).status));assert.ok([403,404].includes((await http('',sender,httpCommand)).status));
  await grant(recipient,'commenter');
  await db.query("UPDATE lanka.materials SET project=jsonb_set(project,'{state,revision}','1') WHERE tenant_id=$1 AND id=$2",[tenant,documentId]);
  for(const blob of captured.blobs)await db.query('INSERT INTO lanka.blobs(tenant_id,material_id,key,bytes) VALUES($1,$2,$3,$4)',[tenant,documentId,'materials/'+blob.hash+'.bin',blob.bytes]);
  if(process.env.LANKA_REVIEW_REAL_AGENT_ONLY==='1'){const {runColleagueRealAgent}=await import('./fixtures/colleague-real-agent.mjs');await runColleagueRealAgent({db,admin,base,tenant,documentId,sender,recipient,users,reviews,keys,origin});return;}
  browser=await chromium.launch({headless:true});const browserContext=await browser.newContext({viewport:{width:1440,height:1000}});await browserContext.addCookies([{name:'review-test',value:tokens[sender],url:origin}]);
  const page=await browserContext.newPage(),pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));
  await page.goto(origin+'/organizations/'+tenant+'/documents/'+documentId);await page.getByRole('button',{name:'Проверка',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'Проверка с коллегой'});await dialog.getByLabel('Имя коллеги',{exact:true}).fill('Test');await dialog.getByRole('button',{name:'Найти коллегу',exact:true}).click();
  await dialog.getByLabel('Коллега',{exact:true}).selectOption(recipient);await dialog.getByLabel('Что проверить',{exact:true}).fill('Браузерная проверка');let lost=false;await page.route('**/review-requests',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;const r=await route.fetch();assert.equal(r.status(),200);await route.abort('failed');}else await route.continue();});
  await dialog.getByRole('button',{name:'Отправить на проверку',exact:true}).click();
  await dialog.getByRole('button',{name:'Повторить отправку',exact:true}).waitFor();await grant(recipient,null);await page.reload();await page.getByRole('button',{name:'Проверка',exact:true}).click();await dialog.getByRole('button',{name:'Повторить отправку',exact:true}).click();await dialog.getByRole('alert').waitFor();await grant(recipient,'commenter');await page.reload();await page.getByRole('button',{name:'Проверка',exact:true}).click();await dialog.getByRole('button',{name:'Повторить отправку',exact:true}).click();
  await dialog.getByRole('status').filter({hasText:'Сохранено.'}).waitFor();
  await mkdir('out/colleague-review-ui',{recursive:true});await page.screenshot({path:'out/colleague-review-ui/sent-desktop.png',fullPage:true});assert.deepEqual(pageErrors,[]);
  const sentRows=(await db.query("SELECT id FROM lanka.colleague_reviews WHERE tenant_id=$1 AND state->>'note'='Браузерная проверка'",[tenant])).rows;assert.equal(sentRows.length,1);const sent=sentRows[0].id;
  const colleagueContext=await browser.newContext({viewport:{width:390,height:844}});await colleagueContext.addCookies([{name:'review-test',value:tokens[recipient],url:origin}]);const colleaguePage=await colleagueContext.newPage();colleaguePage.on('pageerror',e=>pageErrors.push(e.message));
  await colleaguePage.goto(origin+'/organizations/'+tenant);
  const inboxSection=colleaguePage.getByRole('region',{name:'Коллеги ждут проверки'});await inboxSection.locator('li').first().waitFor();
  await grant(recipient,null);await inboxSection.getByText('Входящих запросов пока нет.',{exact:true}).waitFor({timeout:22000});assert.equal(await inboxSection.locator('li').count(),0);
  await grant(recipient,'commenter');await colleaguePage.evaluate(()=>window.dispatchEvent(new Event('focus')));await inboxSection.locator('li').first().waitFor();
  await inboxSection.scrollIntoViewIfNeeded();await colleaguePage.screenshot({path:'out/colleague-review-ui/inbox-mobile.png'});
  const showAll=inboxSection.getByRole('button',{name:'Показать все проверки на странице'});if(await showAll.count())await showAll.click();
  const incomingLink=inboxSection.locator('a[href$="reviewRequest='+sent+'"]');
  if(!await incomingLink.count()){await inboxSection.getByRole('button',{name:'Следующая страница проверок'}).click();await incomingLink.waitFor();}
  await incomingLink.click();const colleagueDialog=colleaguePage.getByRole('dialog',{name:'Проверка с коллегой'});
  await colleagueDialog.getByRole('button',{name:'Отправить ответ',exact:true}).waitFor();
  assert.equal((await colleagueDialog.textContent()).includes('PRIVATE-'),false);
  await colleagueDialog.getByLabel('Комментарий',{exact:true}).fill('Проверено в браузере');await colleaguePage.reload();await colleagueDialog.getByLabel('Комментарий',{exact:true}).waitFor();assert.equal(await colleagueDialog.getByLabel('Комментарий',{exact:true}).inputValue(),'Проверено в браузере');await colleaguePage.screenshot({path:'out/colleague-review-ui/recipient-mobile.png',fullPage:true});
  await colleagueDialog.getByRole('button',{name:'Отправить ответ',exact:true}).click();await colleagueDialog.getByRole('status').filter({hasText:'Сохранено.'}).waitFor();
  assert.equal(new URL(colleaguePage.url()).searchParams.has('reviewRequest'),false);
  const unavailablePage=await colleagueContext.newPage();
  await unavailablePage.goto(origin+'/organizations/'+tenant+'/documents/'+documentId+'?reviewRequest='+randomUUID());
  const unavailableDialog=unavailablePage.getByRole('dialog',{name:'Проверка с коллегой'});await unavailableDialog.getByRole('alert').waitFor();
  assert.equal(await unavailableDialog.locator('.colleague-review-slides').count(),0);await unavailablePage.close();
  const answered=(await db.query('SELECT state FROM lanka.colleague_reviews WHERE tenant_id=$1 AND id=$2',[tenant,sent])).rows[0].state;assert.equal(answered.response.note,'Проверено в браузере');assert.equal(answered.response.actorId,recipient);assert.deepEqual(pageErrors,[]);
  assert.deepEqual((await db.query('SELECT project FROM lanka.materials WHERE tenant_id=$1 AND id=$2',[tenant,documentId])).rows[0].project,project);

  // Select an existing pending request already visible in the current document list.
  const pendingIds=pending.map(r=>r.id);
  const pickPending=async()=>{await colleagueDialog.locator('li').first().waitFor();const id=await colleagueDialog.locator('li').evaluateAll((rows,ids)=>rows.map(r=>r.getAttribute('data-review-id')).find(id=>ids.includes(id)),pendingIds);assert.ok(id);await colleagueDialog.locator('[data-review-id="'+id+'"] button').click();await colleagueDialog.getByRole('button',{name:'Отправить ответ',exact:true}).waitFor();return id;};
  const conflictId=await pickPending();await colleagueDialog.getByLabel('Комментарий',{exact:true}).fill('Ответ перед отменой');
  let cancelledAtSend=false;await colleaguePage.route('**/review-requests',async route=>{
   const request=route.request(),body=request.method()==='POST'?request.postDataJSON():null;
   if(body?.action==='respond'&&body.id===conflictId&&!cancelledAtSend){cancelledAtSend=true;assert.equal((await http('',sender,{action:'cancel',requestId:randomUUID(),id:conflictId,expectedStatusVersion:1})).status,200);}
   await route.continue();
  });
  await colleagueDialog.getByRole('button',{name:'Отправить ответ',exact:true}).click();await colleagueDialog.getByText('Запрос отменён.',{exact:true}).waitFor();
  assert.equal(await colleagueDialog.getByRole('status').filter({hasText:'Сохранено.'}).count(),0);assert.equal(await colleagueDialog.getByLabel('Черновик ответа',{exact:true}).inputValue(),'Ответ перед отменой');assert.equal(await colleagueDialog.getByRole('button',{name:'Отправить ответ',exact:true}).count(),0);
  const cancelledState=(await db.query('SELECT state FROM lanka.colleague_reviews WHERE tenant_id=$1 AND id=$2',[tenant,conflictId])).rows[0].state;assert.equal(cancelledState.status,'cancelled');assert.equal('response' in cancelledState,false);
  await colleaguePage.screenshot({path:'out/colleague-review-ui/cancelled-draft-mobile.png',fullPage:true});
  await colleagueDialog.getByRole('button',{name:'К списку запросов',exact:true}).click();await colleagueDialog.getByRole('button',{name:'Обновить список',exact:true}).click();
  pendingIds.splice(pendingIds.indexOf(conflictId),1);const revokedId=await pickPending();await colleagueDialog.getByLabel('Комментарий',{exact:true}).fill('Ответ после восстановления');
  await grant(recipient,null);await colleagueDialog.locator('.colleague-review-slides').waitFor({state:'hidden',timeout:15000});
  const savedDraft=await colleaguePage.evaluate(id=>Object.keys(sessionStorage).filter(k=>k.includes('colleague-review:v1:')).map(k=>JSON.parse(sessionStorage.getItem(k))).find(d=>d.answers[id])?.answers[id],revokedId);assert.equal(savedDraft.text,'Ответ после восстановления');
  await grant(recipient,'commenter');await colleaguePage.reload();await colleaguePage.getByRole('button',{name:'Проверка',exact:true}).click();await colleagueDialog.getByLabel('Комментарий',{exact:true}).waitFor();assert.equal(await colleagueDialog.getByLabel('Комментарий',{exact:true}).inputValue(),'Ответ после восстановления');
  assert.deepEqual(pageErrors,[]);
  await applySelfHostedMigrations(db);assert.deepEqual((await db.query('SELECT state FROM lanka.colleague_reviews WHERE id=$1',[first.id])).rows[0].state,stored);
  // Persist a maximum-length unbroken note and exercise the actual inbox response.
  const longNote=('Подробное пояснение '.repeat(90)+'А'.repeat(300)).slice(0,2000),longRequest=(await(await inbox()).json()).items[0];assert.ok(longRequest);
  await db.query("UPDATE lanka.colleague_reviews SET state=jsonb_set(state,'{note}',to_jsonb($3::text)) WHERE tenant_id=$1 AND id=$2",[tenant,longRequest.id,longNote]);
  const longPage=await colleagueContext.newPage();await longPage.goto(origin+'/organizations/'+tenant);
  const longInbox=longPage.getByRole('region',{name:'Коллеги ждут проверки'}),longLink=longInbox.locator('a[href$="reviewRequest='+longRequest.id+'"]');await longLink.waitFor();
  assert.ok((await longLink.boundingBox()).height<260,'Long note must not make a huge inbox card');
  assert.equal(await longPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await longInbox.scrollIntoViewIfNeeded();await longPage.screenshot({path:'out/colleague-review-ui/inbox-long-mobile.png'});
  await longLink.click();const longDialog=longPage.getByRole('dialog',{name:'Проверка с коллегой'});await longDialog.getByText(longNote,{exact:true}).waitFor();await longPage.close();
  if(process.env.LANKA_REVIEW_REAL_AGENT==='1'){const {runColleagueRealAgent}=await import('./fixtures/colleague-real-agent.mjs');await runColleagueRealAgent({db,admin,base,tenant,documentId,sender,recipient,users,reviews,keys,origin});}
 }finally{if(browser){await mkdir('out/colleague-review-ui',{recursive:true});await browser.contexts()[0]?.pages()[0]?.screenshot({path:'out/colleague-review-ui/last.png',fullPage:true}).catch(()=>{});const lastPage=browser.contexts().at(-1)?.pages()[0];await lastPage?.screenshot({path:'out/colleague-review-ui/last-recipient.png',fullPage:true}).catch(()=>{});}await browser?.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}await db?.end();if(created)await admin.query(`DROP DATABASE "${name}"`);await admin.end();}
});
