import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';
await build({stdin:{contents:`export {compileCommands} from './lib/domain/commands';export {assertSelectionChanges} from './lib/domain/selection-changes';export {demoDoc} from './lib/domain/model';export {inspectNarrative} from './lib/domain/narrative';`,resolveDir:process.cwd()},outfile:'.project-runtime/slide-intent-test.mjs',bundle:true,platform:'node',format:'esm',packages:'external'});
const {compileCommands,assertSelectionChanges,demoDoc,inspectNarrative}=await import('../../.project-runtime/slide-intent-test.mjs');
const intent={role:'next_step',takeaway:'Согласовать план после разбора причин',transition:'',openQuestions:[]};
test('agent can propose a missing intent without changing slide appearance or saved document',()=>{
 for(const canvas of [false,true]){const doc=demoDoc(),s=doc.slides[0];delete s.intent;if(canvas)s.canvas=[{id:'bg',kind:'rect',x:0,y:0,w:1600,h:900,color:'#123456',locked:true}];const before=structuredClone(doc);const changes=compileCommands(doc,[{op:'set_intent',slideId:s.id,value:intent}]);assert.deepEqual(doc,before);assert.deepEqual(changes[0].after,{...s,intent});assert.doesNotThrow(()=>assertSelectionChanges(doc,changes,{slideId:s.id,scope:'slide'}));assert.throws(()=>assertSelectionChanges(doc,changes,{slideId:s.id,field:'title'}));if(canvas)assert.throws(()=>assertSelectionChanges(doc,changes,{slideId:s.id,elementId:'bg'}));assert.throws(()=>assertSelectionChanges(doc,changes,{slideId:'other'}));const issues=inspectNarrative({...doc,slides:[changes[0].after]});assert.ok(!issues.some(i=>['intent-missing','outcome-missing'].includes(i.code)));}
});
test('intent proposals validate roles and full payload and cannot escape a takeaway selection',()=>{
 const doc=demoDoc(),s=doc.slides[0];s.intent={...intent,role:'context'};for(const value of [{...intent,role:'invented'},{takeaway:'x'},{...intent,hidden:'x'},{...intent,openQuestions:Array(9).fill('x')}])assert.throws(()=>compileCommands(doc,[{op:'set_intent',slideId:s.id,value}]));const changes=compileCommands(doc,[{op:'set_intent',slideId:s.id,value:intent}]);assert.throws(()=>assertSelectionChanges(doc,changes,{slideId:s.id,field:'takeaway'}));
});
