import {DocumentAgentSourcePicker,type DocumentSourceConsent} from './document-agent-source-picker';
import {companionConnection} from '../lib/project/companion-connection.mjs';
import {folderTree} from '../lib/project/library-folders';
import {AgentSourcePicker,type AgentSourceSelection} from './agent-source-picker';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogTitle,DialogTrigger} from './ui/dialog';
import {corporateContext} from '../lib/project/browser-context';
import {localFetch,LocalRequestError} from '../lib/project/local-client';
import {download} from '../lib/project/download';
type Key={documentSources?:DocumentSourceConsent[];folderResourceId?:string|null;sources?:AgentSourceSelection[];id:string;name:string;capabilities:string[];expiresAt:string;revokedAt:string|null};
type Issue={sourceDocumentId?:string;documentSources?:DocumentSourceConsent[];expectedRevision?:number;folderResourceId?:string;folderId?:string;sources?:AgentSourceSelection[];requestId:string;secret:string;name:string;capability:'read'|'comment'|'propose'|'create'|'organize'|'create_shared';minutes:number};
export type AgentFolderScope={resourceId:string|null;label:string;shared:boolean;role?:string};
export function AgentDelegationButton({canComment=true,canPropose=true,compact=false,workspace=false,fixedScope,onIssued,onClose,conversationId,sourceDocumentId}:{sourceDocumentId?:string;conversationId?:string;workspace?:boolean;canComment?:boolean;canPropose?:boolean;compact?:boolean;fixedScope?:AgentFolderScope;onIssued?:(key:Key)=>Promise<void>;onClose?:()=>void}){
 const ctx=corporateContext()!,endpoint=`${location.origin}/mcp/organizations/${ctx.tenantId}${workspace?'':`/documents/${ctx.documentId}`}`,api=workspace?'/api/workspace-delegations':'/api/agent-delegations';
 const [open,setOpen]=useState(false),[keys,setKeys]=useState<Key[]>([]),[name,setName]=useState('Мой агент'),[capability,setCapability]=useState<'read'|'comment'|'propose'|'create'|'organize'|'create_shared'>(()=>onIssued?(fixedScope?.shared?(fixedScope.role==='manager'?'create_shared':fixedScope.role==='editor'?'propose':fixedScope.role==='commenter'?'comment':'read'):'create'):'read'),[minutes,setMinutes]=useState(30),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[issued,setIssued]=useState<{request:Issue;key:Key}|null>(null);
 const [boundSessionId,setBoundSessionId]=useState<string|null>(null);
 const [folders,setFolders]=useState<{id:string;name:string;resourceId:string;parentId?:string|null}[]>([]),[folderId,setFolderId]=useState('');
 const [sharedFolders,setSharedFolders]=useState<{id:string;resourceId:string;name:string;parentId:string|null;role:string}[]>([]);
 const sharedSelection=fixedScope?.shared??folderId.startsWith('shared:'),selectedShared=fixedScope?.shared?fixedScope:sharedFolders.find(f=>'shared:'+f.id===folderId),rank=selectedShared?['viewer','commenter','editor','manager'].indexOf(selectedShared.role??'viewer')+1:0;
 const [documentSources,setDocumentSources]=useState<DocumentSourceConsent[]>([]),[sourceRevision,setSourceRevision]=useState(0);
 const [sources,setSources]=useState<AgentSourceSelection[]>([]),[sourceBusy,setSourceBusy]=useState(false);
 const resultRef=useRef<HTMLElement|null>(null),resultReady=Boolean(issued&&(!onIssued||boundSessionId));
 useEffect(()=>{if(resultReady){resultRef.current?.focus();resultRef.current?.scrollIntoView({block:'start'});}},[resultReady]);
 const pending=useRef<Issue|null>(null),lock=useRef(false);
 useEffect(()=>{if(!open)return;let alive=true;const abort=new AbortController();const load=async()=>{try{const r=await localFetch(api,{signal:abort.signal,cache:'no-store'}),data=await r.json() as {sharedFolders?:{id:string;resourceId:string;name:string;parentId:string|null;role:string}[];delegations:Key[];folders?:{id:string;name:string;resourceId:string;parentId?:string|null}[]};if(alive){setKeys(data.delegations);setFolders(data.folders??[]);setSharedFolders(data.sharedFolders??[]);}}catch(e){if(alive&&!abort.signal.aborted){setKeys([]);setFolders([]);setSharedFolders([]);setError((e as Error).message);}}};void load();const timer=setInterval(()=>void load(),5000);return()=>{alive=false;abort.abort();clearInterval(timer);};},[open,refresh,api]);
 const issue=async()=>{
  if(lock.current||sourceBusy)return;lock.current=true;setBusy(true);setError('');setBoundSessionId(null);
  const request=pending.current??{requestId:crypto.randomUUID(),secret:Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join(''),name:name.trim(),capability,minutes,...(fixedScope?(fixedScope.resourceId?{folderResourceId:fixedScope.resourceId}:{}):workspace&&folderId?(sharedSelection?{folderResourceId:folderId.slice(7)}:{folderId}):{}),...((!workspace||sourceDocumentId)&&documentSources.length?{documentSources,expectedRevision:sourceRevision,...(workspace?{sourceDocumentId}:{})}:{}),...(workspace&&['create','organize','create_shared'].includes(capability)&&sources.length?{sources}: {})};pending.current=request;
  try{const r=await localFetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'issue',request})});const issuedKey=await r.json() as Key;setIssued({request,key:issuedKey});pending.current=null;setRefresh(n=>n+1);if(onIssued)try{await onIssued(issuedKey);if(conversationId)setBoundSessionId(conversationId);}catch(e){throw new Error('Ключ выдан, но беседа не связана: '+(e as Error).message+' Вернитесь в беседу и выберите этот ключ.');}}
  catch(e){if(e instanceof LocalRequestError&&e.status&&e.status<500)pending.current=null;setError((e as Error).message);}
  finally{lock.current=false;setBusy(false);}
 };
 const revoke=async(id:string)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await localFetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'revoke',id})});if(issued?.key.id===id){setIssued(null);setBoundSessionId(null);}setRefresh(n=>n+1);}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}};
 const downloadable=issued&&!issued.key.revokedAt&&Date.parse(issued.key.expiresAt)>Date.now()&&!keys.some(k=>k.id===issued.key.id&&k.revokedAt);
 return <Dialog open={open} onOpenChange={v=>{if(lock.current)return;setOpen(v);if(!v)onClose?.();}}><DialogTrigger asChild><button aria-label="Подключить агента" title="Подключить внешнего агента">{compact?"Доступ агенту":"Подключить агента"}</button></DialogTrigger><DialogContent className="agent-delegation-dialog">
  <DialogTitle>{onIssued?'Подключение к беседе':workspace?'Агент для библиотеки':'Агент для этой презентации'}</DialogTitle><DialogDescription>{fixedScope?'Ключ ограничен областью этой беседы. Права на презентации проверяются при каждом обращении.':workspace?'Выберите библиотеку целиком или папку проекта. Агент увидит доступные презентации в выбранной области и шаблоны. При изменении ваших прав доступ агента тоже изменится.':'Ключ действует только для текущей презентации. Агент сможет читать видимые слайды и общие обсуждения.'} {onIssued?'При выдаче вы также разрешаете этому ключу читать всю переписку выбранной беседы и отвечать в ней через MCP. После успешной привязки изменения этим ключом будут разрешены только по активным поручениям; самостоятельная запись ключом станет недоступна.':'Родной чат агента остаётся в его приложении; доступ к беседе Lanka выдаётся отдельно.'}</DialogDescription>
  {error&&<p role="alert">{error}</p>}
  {downloadable&&<section ref={resultRef} tabIndex={-1} aria-label="Подключение готово"><p>Доступ выдан до {new Date(issued.key.expiresAt).toLocaleTimeString('ru-RU')}. {onIssued?'Скачайте подключение к беседе и настройте локального агента.':'Скачайте настройки и добавьте MCP-сервер в приложении агента.'}</p><button onClick={()=>download(new Blob([JSON.stringify({mcpServers:{lanka:{url:endpoint,headers:{Authorization:`Bearer ${issued.request.secret}`}}}},null,2)],{type:'application/json'}),`lanka-agent-${issued.key.id}.json`)}>Скачать настройки MCP</button>{workspace&&boundSessionId===conversationId&&boundSessionId&&<><button onClick={()=>download(new Blob([JSON.stringify(companionConnection({format:'lanka-companion-connection/v1',url:endpoint,token:issued.request.secret,sessionId:boundSessionId,expiresAt:issued.key.expiresAt}),null,2)],{type:'application/json'}),`lanka-conversation-${boundSessionId}.json`)}>Скачать подключение к беседе</button><p className="hint">После скачивания запустите мастер из корня локальной установки Lanka:</p><pre><code>node runtime/companion-setup.mjs</code></pre><p className="hint">Укажите скачанный файл. Мастер подготовит отдельный профиль и покажет команду панели. Откройте панель, войдите в Codex, проверьте подключение и нажмите «Запустить». Затем вернитесь в беседу и отправьте поручение. Если Lanka установлена только на сервере, локальную установку должен подготовить администратор.</p></>}<p className="hint">Файл содержит ключ доступа. Не публикуйте его. После обновления страницы ключ нельзя скачать повторно; можно отозвать его и выдать новый.</p></section>}
  <label>Название подключения<input aria-label="Название подключения агента" maxLength={100} value={name} disabled={busy||sourceBusy||!!pending.current} onChange={e=>setName(e.target.value)}/></label>
  {fixedScope&&<p>Область беседы: <strong>{fixedScope.label}</strong></p>}
  {workspace&&!fixedScope&&<label>Область доступа<select aria-label="Область доступа агента" value={folderId} disabled={busy||sourceBusy||!!pending.current} onChange={e=>{setFolderId(e.target.value);setCapability('read');}}><option value="">Вся доступная библиотека</option>{folderTree(folders).map(f=><option key={f.id} value={f.id}>{f.path}</option>)}{folderTree(sharedFolders).map(f=><option key={'shared:'+f.id} value={'shared:'+f.id}>Общие · {f.path}</option>)}</select><span className="hint">{sharedSelection?'Общая папка: доступны просмотр, комментарии и предложения в пределах ваших текущих прав. Для создания выберите отдельное разрешение; оно требует управления папкой.':folderId?'Только выбранная папка и вложенные папки. Документ, перенесённый наружу, станет недоступен агенту.':'Агент получит доступ ко всем доступным вам презентациям организации. Для отдельного проекта выберите папку.'}</span></label>}
  <label>Разрешения<select aria-label="Разрешения агента" value={capability} disabled={busy||sourceBusy||!!pending.current} onChange={e=>setCapability(e.target.value as 'read'|'comment'|'propose'|'create'|'organize'|'create_shared')}><option value="read">Только просмотр</option>{workspace?<><option value="comment" disabled={sharedSelection&&rank<2}>Просмотр и комментарии</option><option value="propose" disabled={sharedSelection&&rank<3}>Комментарии и предложения правок</option><option value="create" disabled={sharedSelection}>Создание, комментарии и предложения правок</option><option value="create_shared" disabled={!sharedSelection||rank<4}>Создание в общей папке</option><option value="organize" disabled={sharedSelection}>Создание и управление личной библиотекой</option></>:<><option value="comment" disabled={!canComment}>Просмотр и общие комментарии</option><option value="propose" disabled={!canPropose}>Просмотр, комментарии и предложения правок</option></>}</select></label>
  <label>Срок<select aria-label="Срок доступа агента" value={minutes} disabled={busy||sourceBusy||!!pending.current} onChange={e=>setMinutes(Number(e.target.value))}>{[15,30,60].map(n=><option key={n} value={n}>{n} минут</option>)}</select></label>
  {capability!=='read'&&<p className="hint">{capability==='create_shared'?"Новые презентации и папки будут принадлежать вам и наследовать доступ выбранной папки. Видимое содержание станет доступно её участникам; личные заметки не передаются. Изменение прав этим ключом недоступно.":capability==='organize'?"Агент сможет переименовывать, переносить, копировать ваши презентации и отправлять их в корзину. Перенос меняет унаследованный доступ; корзина останавливает задания. Копии сохраняют исходники и заметки для вас. Также доступны создание, копии с разрешения владельцев, комментарии и предложения правок.":capability==='create'?"Агент сможет создавать презентации и папки в вашей библиотеке, копировать общие слайды с разрешения владельца, писать общие комментарии и предлагать правки там, где у вас есть права. Личные заметки не передаются.":capability==='propose'?"Агент получит редактируемое содержание и сможет предлагать правки. Владелец проверяет и принимает их. Личные заметки не передаются.":"Комментарии агента видны всем участникам с доступом. Изменение слайдов этим ключом недоступно."}</p>}
  {(!workspace||sourceDocumentId)&&<details><summary>Источники презентации · необязательно</summary><DocumentAgentSourcePicker documentId={sourceDocumentId} value={documentSources} onChange={(values,revision)=>{setDocumentSources(values);setSourceRevision(revision);}} disabled={busy||!!pending.current} onBusy={setSourceBusy}/></details>}
  {workspace&&['create','organize','create_shared'].includes(capability)&&(sourceDocumentId?<details><summary>Материалы для новых презентаций · необязательно</summary><AgentSourcePicker value={sources} onChange={setSources} disabled={busy||sourceBusy||!!pending.current} onBusy={setSourceBusy}/></details>:<AgentSourcePicker value={sources} onChange={setSources} disabled={busy||sourceBusy||!!pending.current} onBusy={setSourceBusy}/>)}
  <button className="agent-issue-action" disabled={busy||sourceBusy||!name.trim()||(sharedSelection&&!selectedShared)||!!(onIssued&&downloadable)} onClick={()=>void issue()}>{busy?'Выполняем…':pending.current?'Повторить выдачу':onIssued?'Выдать ключ и связать беседу':workspace?'Выдать доступ к библиотеке':'Выдать доступ к этой презентации'}</button>

  <details><summary>Адрес сервера и способ подключения</summary><p style={{overflowWrap:'anywhere'}}>{endpoint}</p><p>Streamable HTTP, Bearer-ключ, протокол 2025-06-18. Формат импорта настроек зависит от приложения агента. Автоматический OAuth-вход пока не поддерживается.</p></details>
  <h3>{workspace?'Мои подключения к библиотеке':'Мои подключения к этой презентации'}</h3>
  {!keys.length&&<p className="hint">Подключений пока нет.</p>}
  {keys.filter(k=>!fixedScope||(k.folderResourceId??null)===fixedScope.resourceId).map(k=><article key={k.id}><strong>{k.name}</strong>{workspace&&<p className="hint">{k.folderResourceId?`Папка: ${folderTree(folders).find(f=>f.resourceId===k.folderResourceId)?.path??folderTree(sharedFolders).find(f=>f.resourceId===k.folderResourceId)?.path??'недоступна'}`:'Вся доступная библиотека'}</p>}{!!k.documentSources?.length&&<p className="hint">Разрешено текстовых источников: {k.documentSources.length}</p>}{!!k.sources?.length&&<p className="hint">Передано материалов: {k.sources.length}</p>}<p>{k.capabilities.includes('create_shared')?'Создание в общей папке':k.capabilities.includes('organize')?'Создание и управление библиотекой':k.capabilities.includes('create')?'Создание, комментарии и предложения':k.capabilities.includes('propose')?'Просмотр, комментарии и предложения':k.capabilities.includes('comment')?'Просмотр и комментарии':'Просмотр'} · {k.revokedAt?'Отозван':Date.parse(k.expiresAt)<=Date.now()?'Истёк':`до ${new Date(k.expiresAt).toLocaleTimeString('ru-RU')}`}</p>{!k.revokedAt&&Date.parse(k.expiresAt)>Date.now()&&<button disabled={busy} onClick={()=>void revoke(k.id)}>Отозвать {k.name}</button>}</article>)}
 </DialogContent></Dialog>;
}
