import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogTitle,DialogTrigger} from './ui/dialog';
import {folderTree,type LibraryFolder} from '../lib/project/library-folders';
import {localFetch,LocalRequestError} from '../lib/project/local-client';
import {documentPath} from '../lib/project/browser-context';
import type {DocumentView} from '../lib/project/document-view';
export function SharedCopyButton({view,publicationId,inline=false,onCancel,onPendingChange}:{view:Pick<DocumentView,'title'|'revision'>;publicationId?:string;inline?:boolean;onCancel?:()=>void;onPendingChange?:(pending:boolean)=>void}){
 const [open,setOpen]=useState(inline),[folders,setFolders]=useState<LibraryFolder[]>([]),[folderId,setFolderId]=useState(''),[title,setTitle]=useState((view.title+' — копия').slice(0,140)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const pending=useRef<{requestId:string;expectedRevision:number;title:string;folderId:string|null}|null>(null),lock=useRef(false);
 useEffect(()=>{if(!open)return;const abort=new AbortController();void localFetch('/api/library',{signal:abort.signal,cache:'no-store'}).then(r=>r.json() as Promise<{folders:LibraryFolder[]}>).then(v=>{if(!abort.signal.aborted)setFolders(v.folders);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[open]);
 const copy=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');const request=pending.current??{requestId:crypto.randomUUID(),expectedRevision:view.revision,title:title.trim(),folderId:folderId||null};pending.current=request;onPendingChange?.(true);
  try{const r=await localFetch('/api/document-copy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...request,...(publicationId?{publicationId}:{})})}),result=await r.json() as {id:string};pending.current=null;onPendingChange?.(false);location.assign(documentPath(result.id));}
  catch(e){if(e instanceof LocalRequestError&&e.status&&e.status<500){pending.current=null;onPendingChange?.(false);}setError((e as Error).message);}
  finally{lock.current=false;setBusy(false);}
 };
 const form=<>  <form className="shared-copy-form" onSubmit={e=>{e.preventDefault();void copy();}}><label>Название<input aria-label="Название общей копии" required maxLength={140} value={title} disabled={busy||!!pending.current} onChange={e=>setTitle(e.target.value)}/></label><label>Папка<select aria-label="Папка общей копии" value={folderId} disabled={busy||!!pending.current} onChange={e=>setFolderId(e.target.value)}><option value="">Без папки</option>{folderTree(folders).map(f=><option key={f.id} value={f.id}>{f.path}</option>)}</select></label><p className="hint">В источниках копии останется снимок слайдов версии {pending.current?.expectedRevision??view.revision}. Он фиксирует содержание презентации, но не заменяет проверку исходных данных.</p>{error&&<p role="alert">{error}</p>}<button disabled={busy||!title.trim()}>{busy?'Копируем…':pending.current?'Повторить копирование':'Создать и открыть копию'}</button></form></>;
 if(inline)return <section className="publication-copy-form" aria-label="Копия в вашей библиотеке"><h3>Копия в вашей библиотеке</h3><p>Независимая копия опубликованной версии с редактируемыми объектами.</p>{form}<button disabled={busy||!!pending.current} onClick={onCancel}>Отменить копирование</button></section>;
 return <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogTrigger asChild><button>{publicationId?'Создать на основе':'Создать свою копию'}</button></DialogTrigger><DialogContent className="agent-delegation-dialog"><DialogTitle>Копия в вашей библиотеке</DialogTitle><DialogDescription>Сохранится оформление доступных слайдов и редактируемые объекты. Личные заметки, переписка и оригинальные исходные файлы владельца не переносятся. Копия независима от оригинала.</DialogDescription>{form}</DialogContent></Dialog>;
}
