import {MessageSquare,ArrowUp} from 'lucide-react';
import {ChatMarkdown} from './chat-markdown';
import {CompanionPanelLink} from './companion-panel-link';
import {bridgeMessageStatus,type BridgeExecutionView} from '../lib/project/bridge-status';
import {bridgeTaskSchema} from '../lib/project/bridge-task';
import {bridgeSelectionSchema,type BridgeSelection} from '../lib/project/bridge-selection';
import {AgentDelegationButton,type AgentFolderScope} from './agent-delegation';
import {folderTree} from '../lib/project/library-folders';
import {DocumentCover} from './document-cover';
import {z} from 'zod';
import {scopedStorage} from '../lib/project/browser-context';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogTitle,DialogTrigger} from './ui/dialog';
import {localFetch,LocalRequestError} from '../lib/project/local-client';
type Task=z.infer<typeof bridgeTaskSchema>;
const taskLabels:Record<Task["mode"],string>={discuss:"Обсудить",propose:"Предложить правки",create:"Создать презентацию",comment:"Опубликовать комментарий",organize:"Упорядочить библиотеку"};
const draftSchema=z.object({mode:bridgeTaskSchema.shape.mode.optional(),attachSelection:z.boolean().optional(),id:z.string().uuid().or(z.literal('')),text:z.string().max(12000),folderResourceId:z.string().uuid().nullable().optional(),pending:z.object({sessionId:z.string().uuid(),requestId:z.string().uuid(),text:z.string().min(1).max(12000),create:z.boolean(),folderResourceId:z.string().uuid().nullable().optional(),documentId:z.string().uuid().optional(),selection:bridgeSelectionSchema.optional(),task:bridgeTaskSchema.optional()}).nullable()});
const saveDraft=(value:z.infer<typeof draftSchema>,key:string)=>scopedStorage(sessionStorage).setItem(key,JSON.stringify(value));
type Session={id:string;title:string;folderResourceId:string|null};
type Key={capabilities:string[];id:string;name:string;folderResourceId:string|null;expiresAt:string;revokedAt:string|null};
type Result={available:false}|{available:true;documentId:string;title:string;revision:number;currentRevision:number;proposalId?:string;proposalTitle?:string;proposalStatus?:string;proposalKind?:"draft"|"edits";proposalSlideCount?:number;proposalDecision?:string;url:string};
type Message={id:string;sequence:string;role:'user'|'assistant';text:string;delivery:string;execution?:BridgeExecutionView;task?:(Task&{available?:boolean})|null;results?:Result[];selection?:{available:boolean;revision?:number;stale?:boolean;targetExists?:boolean;elementId?:string;field?:string}};
type Folder={id:string;resourceId:string;name:string;parentId?:string|null;role?:string};
type View={session:Session;documents:{id:string;title:string;revision:number}[];binding:{id:string;name:string;active:boolean;taskBound:boolean}|null;messages:Message[];hasMore:boolean;nextCursor:string};
function MessageExecutionStatus({message,taskBound}:{message:Message;taskBound:boolean|undefined}){
 const status=bridgeMessageStatus(message.delivery,message.execution,taskBound);
 return <div className="workspace-chat-execution" data-tone={status.tone}><strong>{status.label}</strong>{status.detail&&<small>{status.detail}</small>}</div>;
}
export function WorkspaceChat({openRequest=0,emptyDraft=false,documentId,embedded=false,documentBusy=false,onReview,selection,selectionLabel}:{openRequest?:number;selection?:BridgeSelection;selectionLabel?:string;documentId?:string;emptyDraft?:boolean;embedded?:boolean;documentBusy?:boolean;onReview?:(id:string)=>void}){
 const [open,setOpen]=useState(embedded),[sessions,setSessions]=useState<Session[]>([]),[listCursor,setListCursor]=useState<string|null>(null),[id,setId]=useState(''),[view,setView]=useState<View|null>(null),[keys,setKeys]=useState<Key[]>([]),[key,setKey]=useState(''),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[pageLimit,setPageLimit]=useState(100);
 useEffect(()=>{if(openRequest>0)setOpen(true);},[openRequest]);
 const [attachSelection,setAttachSelection]=useState(!emptyDraft),[mode,setMode]=useState<Task["mode"]>(emptyDraft?"propose":"discuss");
 const actionLabel=(value:Task["mode"])=>emptyDraft&&value==="propose"?"Заполнить эту презентацию":emptyDraft&&value==="create"?"Создать другую презентацию":taskLabels[value];
 const [folderResourceId,setFolderResourceId]=useState(''),[folders,setFolders]=useState<AgentFolderScope[]>([]);
 const draftKey='workspace-chat-draft'+(documentId?':'+documentId:'');
 const persist=(value:z.infer<typeof draftSchema>)=>saveDraft({...value,attachSelection,mode},draftKey);
 const initialChoice=useRef(false),restoredDraft=useRef<z.infer<typeof draftSchema>|null>(null);
 const composer=useRef<HTMLTextAreaElement|null>(null);
 const journal=useRef<HTMLDivElement|null>(null),nearBottom=useRef(true);
 useEffect(()=>{nearBottom.current=true;},[id]);
 useEffect(()=>{if(nearBottom.current&&journal.current)journal.current.scrollTop=journal.current.scrollHeight;},[view]);
 const lock=useRef(false),pending=useRef<z.infer<typeof draftSchema>['pending']>(null);
 const [restored,setRestored]=useState(false);
 useEffect(()=>{try{const raw=scopedStorage(sessionStorage).getItem(draftKey);if(raw){const draft=draftSchema.parse(JSON.parse(raw));restoredDraft.current=draft;setMode(draft.mode??"discuss");setAttachSelection(draft.attachSelection??true);setId(draft.id);setText(draft.text);setFolderResourceId(draft.folderResourceId??'');pending.current=draft.pending;}}catch{setError('Не удалось восстановить черновик этой вкладки.');}setRestored(true);},[]);
 useEffect(()=>{if(restored)try{persist({id,text,pending:pending.current,folderResourceId:folderResourceId||null});}catch{setError('Не удалось сохранить черновик в этой вкладке. Не закрывайте её до отправки.');}},[id,text,busy,restored,folderResourceId,attachSelection,mode]);
 const post=async(path:string,body:unknown)=>(await localFetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})).json();
 async function list(more=false){const query=new URLSearchParams();if(more&&listCursor)query.set('after',listCursor);if(documentId)query.set('documentId',documentId);
  const r=await(await localFetch('/api/conversations?'+query)).json() as {sessions:Session[];nextCursor:string|null};setSessions(old=>more?[...old,...r.sessions]:r.sessions);setListCursor(r.nextCursor);
  if(documentId&&!initialChoice.current){initialChoice.current=true;if(!restoredDraft.current?.id&&!restoredDraft.current?.text)setId(r.sessions[0]?.id??'');}
 }
 useEffect(()=>{if(!open)return;let alive=true;void Promise.all([list(),localFetch('/api/workspace-delegations').then(r=>r.json() as Promise<{delegations:Key[];folders?:Folder[];sharedFolders?:Folder[]}>)]).then(([,r])=>{if(alive){setKeys(r.delegations);setFolders([...folderTree(r.folders??[]).map(f=>({resourceId:f.resourceId,label:f.path,shared:false,role:'manager'})),...folderTree(r.sharedFolders??[]).map(f=>({resourceId:f.resourceId,label:'Общие · '+f.path,shared:true,role:f.role}))]);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[open,refresh]);
 useEffect(()=>{if(!open||!id){setView(null);return;}let alive=true,running=false;const controller=new AbortController();
  const read=async()=>{if(running)return;running=true;try{let after='0',next:View,all:Message[]=[];do{next=await(await localFetch('/api/conversations/'+id+'?after='+after,{signal:controller.signal})).json();all.push(...next.messages);after=next.nextCursor;}while(next.hasMore&&all.length<pageLimit);if(alive)setView({...next,messages:all});}catch(e){if(alive){setView(null);setError((e as Error).message);}}finally{running=false;}};
  void read();const timer=setInterval(()=>void read(),3000);return()=>{alive=false;controller.abort();clearInterval(timer);};
 },[open,id,refresh,pageLimit]);
 async function perform(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();setRefresh(n=>n+1);}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 async function send(){if(unsupportedMode){setError('У этого подключения нет права выполнить выбранное действие. Выберите другое подключение или выдайте подходящий ключ.');return;}if(documentBusy){setError('Дождитесь сохранения ручных правок перед отправкой.');return;}await perform(async()=>{
  const usesDocument=mode!=="create"&&mode!=="organize";
  const p=pending.current??{sessionId:id||crypto.randomUUID(),requestId:crypto.randomUUID(),text:text.trim(),create:!id,folderResourceId:folderResourceId||null,...(documentId?{documentId}:{}),...(usesDocument&&attachSelection&&selection?{selection}:{}),task:{mode,...(mode==="propose"&&attachSelection&&selection?{limitToSelection:true}:{}),...(usesDocument&&documentId?{documentId}:{})}};pending.current=p;persist({id:p.sessionId,text:p.text,pending:p});
  try{if(p.create){await post('/api/conversations',{requestId:p.sessionId,title:p.text.slice(0,70),folderResourceId:p.folderResourceId??null});p.create=false;persist({id:p.sessionId,text:p.text,pending:p});setId(p.sessionId);}
  if(p.documentId)await post('/api/conversations/'+p.sessionId,{action:'link',documentId:p.documentId});await post('/api/conversations/'+p.sessionId,{action:'send',requestId:p.requestId,text:p.text,...(p.selection?{selection:p.selection}:{}),...(p.task?{task:p.task}:{})});pending.current=null;persist({id:p.sessionId,text:'',pending:null});setText('');nearBottom.current=true;}
  catch(e){if(e instanceof LocalRequestError&&e.status!==undefined&&e.status<500){pending.current=null;if(p.create)setId('');}throw e;}
 });requestAnimationFrame(()=>composer.current?.focus());}
 const selected=view?.session??sessions.find(s=>s.id===id),scope=selected?.folderResourceId?folders.find(f=>f.resourceId===selected.folderResourceId):{resourceId:null,label:'Вся доступная библиотека',shared:false},available=keys.filter(k=>!k.revokedAt&&Date.parse(k.expiresAt)>Date.now()&&(k.folderResourceId??null)===(selected?.folderResourceId??null));
 const activeKey=keys.find(k=>k.id===view?.binding?.id),effectiveMode=pending.current?.task?.mode??mode,unsupportedMode=!!view?.binding?.active&&!!activeKey&&effectiveMode!=="discuss"&&!activeKey.capabilities.includes(effectiveMode);
 const displayedSelection=pending.current?pending.current.selection:attachSelection?selection:undefined;
 const scopeSummary=['create','organize'].includes(effectiveMode)?'Область беседы':displayedSelection?(pending.current?'Выбранная область':selectionLabel??'Выбранный слайд или объект'):documentId?'Вся презентация':'Область беседы';
 const ScopeSettings=embedded?'details':'div';
 const content=<>{embedded?<><h2 className="workspace-chat-title">Беседа об этой презентации</h2><p className="workspace-chat-description">Ваш агент через MCP. Переписка доступна только вам и выбранному подключению.</p></>:<><DialogTitle>Беседы с вашим агентом</DialogTitle><DialogDescription>Личная беседа с вашим агентом через MCP. Он получает сообщения, пока подключён и проверяет очередь.</DialogDescription></>}
   <div className="workspace-chat-navigation"><label>Беседа<select aria-label="Беседа" value={id} disabled={busy||!!pending.current} onChange={e=>{setId(e.target.value);setView(null);setPageLimit(100);setError('');}}><option value="">Новая беседа</option>{selected&&!sessions.some(s=>s.id===selected.id)&&<option value={selected.id}>{selected.title}</option>}{sessions.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>{listCursor&&<button disabled={busy} onClick={()=>void list(true).catch(e=>setError(e.message))}>Ещё беседы</button>}</div>
   <ScopeSettings className="workspace-chat-material-scope">
    {embedded&&<summary>Доступные материалы для беседы</summary>}
    {!id&&<label>Область беседы<select aria-label="Область беседы" value={folderResourceId} disabled={busy||!!pending.current} onChange={e=>setFolderResourceId(e.target.value)}><option value="">Вся доступная библиотека</option>{folders.map(f=><option key={f.resourceId} value={f.resourceId!}>{f.label}</option>)}</select></label>}
    {id&&scope&&<p className="workspace-chat-scope">{scope.resourceId?'Папка: '+scope.label:scope.label}</p>}
    {embedded&&<p className="workspace-chat-material-hint">Это область доступа подключения. Действие и область текущего поручения выбираются перед сообщением ниже.</p>}
   </ScopeSettings>
   {id&&view&&<details className="workspace-chat-binding"><summary>{view.binding?.active?`Подключение: ${view.binding.name}`:view.binding?'Доступ агента закончился — выберите подключение':'Подключите агента к этой беседе'}</summary>
    <p>Подключите своего агента, чтобы он получал сообщения и отвечал здесь.</p>
    {available.length>0&&<label>Выданный ключ<select aria-label="Подключение к беседе" value={key} disabled={busy} onChange={e=>setKey(e.target.value)}><option value="">Выберите выданный ключ</option>{available.map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select></label>}
    {scope&&<AgentDelegationButton sourceDocumentId={documentId} conversationId={id} key={id+':'+scope.resourceId} workspace fixedScope={scope} onIssued={async k=>{await post('/api/conversations/'+id,{action:'bind',delegationId:k.id,expectedDelegationId:view.binding?.id??null,taskBound:true});setRefresh(n=>n+1);}} onClose={()=>setRefresh(n=>n+1)}/>}

    {available.length>0&&<button disabled={busy||!key||!available.some(k=>k.id===key)} onClick={()=>void perform(async()=>{await post('/api/conversations/'+id,{action:'bind',delegationId:key,expectedDelegationId:view.binding?.id??null,taskBound:true});setKey('');})}>Подключить к поручениям</button>}
    <CompanionPanelLink key={id} sessionId={id}/>
    <details className="workspace-chat-binding-info"><summary>Доступ и ограничения</summary><p>Агент получит всю переписку беседы. Запись этим ключом будет разрешена только по активным поручениям, в том числе после смены беседы. Чтение останется в области ключа. Это не зеркало родного чата агента; для ответов здесь нужен работающий исполнитель.</p></details>
   </details>}
   {view?.binding&&!view.binding.taskBound&&<p className="workspace-chat-legacy">Это подключение пока может изменять документы самостоятельно. Выберите его в настройках беседы и нажмите «Подключить к поручениям», чтобы режим сообщения и отмена ограничивали запись.</p>}
   {error&&<p className="chat-error" role="alert">{error}</p>}
   <div ref={journal} onScroll={()=>{const el=journal.current;if(el)nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<60;}} className="workspace-chat-journal" aria-label="Переписка">{!id?<div className="workspace-chat-empty"><MessageSquare size={24} aria-hidden="true"/><h3>Что подготовить или улучшить?</h3><p>Опишите задачу своими словами. Мы сохраним беседу; подключить своего агента можно следующим шагом.</p><small>Личная беседа · видна вам и выбранному подключению</small></div>:!view?<p>Загружаем беседу…</p>:view.messages.map(m=><article key={m.id} data-role={m.role}><strong>{m.role==='user'?'Вы':'Агент · через MCP'}</strong>{m.role==='assistant'?<ChatMarkdown text={m.text}/>:<p>{m.text}</p>}{m.task&&<small>{taskLabels[m.task.mode]}{m.task.limitToSelection?" · только выбранная область":""}{m.task.available===false?" · документ недоступен":""}</small>}{m.selection&&<small className="workspace-chat-selection">{!m.selection.available?'Контекст больше недоступен':`${m.selection.elementId?'Выбранный объект':m.selection.field?'Выбранное поле':'Выбранный слайд'} · версия ${m.selection.revision}${m.selection.stale?' · документ изменился':''}${m.selection.targetExists===false?' · объект удалён':''}`}</small>}{m.results?.map((r,i)=>r.available?<a key={i} className="workspace-chat-result" href={r.url} aria-disabled={documentBusy} onClick={e=>{if(documentBusy){e.preventDefault();setError("Дождитесь сохранения правок перед переходом.");}else if(r.documentId===documentId&&r.proposalId&&onReview){e.preventDefault();onReview(r.proposalId);}}}><DocumentCover documentId={r.documentId} revision={r.currentRevision} title={r.title}/><span><strong>{r.proposalTitle??r.title}</strong>{r.proposalTitle&&<span>{r.title}</span>}{r.proposalSlideCount!==undefined&&<small>{r.proposalKind==="draft"?"Первое заполнение":"Правки"} · слайдов: {r.proposalSlideCount}</small>}<small>Версия ответа: {r.revision}{r.currentRevision!==r.revision?` · текущая: ${r.currentRevision}`:''}</small>{r.proposalId&&<small>{r.proposalStatus==='pending'?'Ожидает проверки':r.proposalDecision==='accepted'?'Рассмотрено · принято':r.proposalDecision==='rejected'?'Рассмотрено · отклонено':r.proposalDecision==='mixed'?'Рассмотрено · принято частично':'Рассмотрено'}</small>}<span className="workspace-chat-result-action">{r.proposalId?'Посмотреть изменения':'Открыть презентацию'} →</span></span></a>:<p key={i} className="workspace-chat-result-unavailable">Результат больше недоступен.</p>)}{m.role==='user'&&<MessageExecutionStatus message={m} taskBound={view.binding?.taskBound}/>}{m.role==='user'&&['waiting','received_by_mcp_client'].includes(m.delivery)&&<button disabled={busy} onClick={()=>void perform(async()=>{await post('/api/conversations/'+id,{action:'cancel',messageId:m.id});})}>{view.binding?.taskBound?"Отменить поручение":"Отменить ожидание"}</button>}</article>)}{view?.hasMore&&<button onClick={()=>setPageLimit(n=>n+100)}>Следующие сообщения</button>}</div>
   <details className="workspace-chat-options">
    <summary>{actionLabel(effectiveMode)} · {scopeSummary}</summary>
   <label className="workspace-chat-mode">Действие<select aria-label="Действие агента" value={pending.current?.task?.mode??mode} disabled={busy||!!pending.current} onChange={e=>setMode(bridgeTaskSchema.shape.mode.parse(e.target.value))}>{Object.entries(taskLabels).map(([value,label])=><option key={value} value={value}>{actionLabel(value as Task["mode"])}</option>)}</select></label>
   {selection&&!['create','organize'].includes(pending.current?.task?.mode??mode)&&<label className="workspace-chat-target"><input type="checkbox" checked={pending.current?!!pending.current.selection:attachSelection} disabled={busy||!!pending.current} onChange={e=>setAttachSelection(e.target.checked)}/><span>{pending.current?'Контекст зафиксирован для повторной отправки':attachSelection?(selectionLabel??'Выбранный слайд')+' · версия '+selection.revision:'Вся презентация'}<small>{(pending.current?.task?.mode??mode)==="propose"?"Разрешить правки только в выбранной области":"Прикрепить выбранный слайд или объект"}</small></span></label>}
   </details>
   {unsupportedMode&&<p className="chat-error" role="status">У подключения нет права выполнить это действие. Выберите другое подключение в настройках беседы.</p>}
   <small className="workspace-chat-task-scope">{(pending.current?.task?.mode??mode)==="discuss"?view?.binding&&!view.binding.taskBound?"Запрос на обсуждение · старый ключ не ограничен":"Без изменения документов":(pending.current?.task?.mode??mode)==="propose"?"Предложение для вашей проверки":(pending.current?.task?.mode??mode)==="comment"?"Комментарий увидят участники документа":"В области этой беседы"}{documentId&&!['create','organize'].includes(pending.current?.task?.mode??mode)?" · эта презентация":""}</small>
   <form className="workspace-chat-compose" onSubmit={e=>{e.preventDefault();if(text.trim()||pending.current)void send();}}><label htmlFor="workspace-chat-message">Сообщение</label><textarea ref={composer} id="workspace-chat-message" value={text} maxLength={12000} disabled={busy||!!pending.current} onChange={e=>setText(e.target.value)} placeholder="Например: подготовь 6 слайдов о первых цивилизациях"/><button disabled={busy||documentBusy||unsupportedMode||(!text.trim()&&!pending.current)}><ArrowUp size={16} aria-hidden="true"/>{busy?'Сохраняем…':pending.current?'Повторить отправку':'Отправить'}</button></form>
   <details className="workspace-chat-note"><summary>Как работает ожидание и отмена</summary><p>Для подключения к поручениям отмена закрывает дальнейшие операции записи этого поручения. Уже начатая запись может завершиться до подтверждения отмены; сохранённые результаты остаются. Сам внешний процесс не остановлен. Самостоятельный старый ключ продолжает работать: для прекращения его доступа отзовите ключ в настройках агента.</p></details>
  </>;
 if(embedded)return <section className="workspace-chat-dialog workspace-chat-inline">{content}</section>;
 return <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogTrigger asChild><button className="text-link">Беседы с агентом</button></DialogTrigger><DialogContent className="workspace-chat-dialog" showCloseButton={!busy}>{content}</DialogContent></Dialog>;
}
